/* tslint:disable */
/* eslint-disable */
/**
 * My App
 * This is an awesome app!
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiAuthPost200Response,
  ApiAuthPostRequest,
} from '../models/index';
import {
    ApiAuthPost200ResponseFromJSON,
    ApiAuthPost200ResponseToJSON,
    ApiAuthPostRequestFromJSON,
    ApiAuthPostRequestToJSON,
} from '../models/index';

export interface ApiAuthPostOperationRequest {
    apiAuthPostRequest: ApiAuthPostRequest;
}

/**
 * 
 */
export class LoginApi extends runtime.BaseAPI {

    /**
     * Login into the api.
     */
    async apiAuthPostRaw(requestParameters: ApiAuthPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiAuthPost200Response>> {
        if (requestParameters['apiAuthPostRequest'] == null) {
            throw new runtime.RequiredError(
                'apiAuthPostRequest',
                'Required parameter "apiAuthPostRequest" was null or undefined when calling apiAuthPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/auth`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ApiAuthPostRequestToJSON(requestParameters['apiAuthPostRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiAuthPost200ResponseFromJSON(jsonValue));
    }

    /**
     * Login into the api.
     */
    async apiAuthPost(requestParameters: ApiAuthPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiAuthPost200Response> {
        const response = await this.apiAuthPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
