/* tslint:disable */
/* eslint-disable */
/**
 * My App
 * This is an awesome app!
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GetUserNotifications200ResponseInner,
  SendNotificationRequest,
  TestNotificationRequest,
} from '../models/index';
import {
    GetUserNotifications200ResponseInnerFromJSON,
    GetUserNotifications200ResponseInnerToJSON,
    SendNotificationRequestFromJSON,
    SendNotificationRequestToJSON,
    TestNotificationRequestFromJSON,
    TestNotificationRequestToJSON,
} from '../models/index';

export interface GetUserNotificationsRequest {
    limit?: number;
}

export interface SendNotificationOperationRequest {
    sendNotificationRequest: SendNotificationRequest;
}

export interface TestNotificationOperationRequest {
    testNotificationRequest: TestNotificationRequest;
}

/**
 * 
 */
export class NotificationApi extends runtime.BaseAPI {

    /**
     * Get user notifications
     */
    async getUserNotificationsRaw(requestParameters: GetUserNotificationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<GetUserNotifications200ResponseInner>>> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/notifications`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(GetUserNotifications200ResponseInnerFromJSON));
    }

    /**
     * Get user notifications
     */
    async getUserNotifications(requestParameters: GetUserNotificationsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<GetUserNotifications200ResponseInner>> {
        const response = await this.getUserNotificationsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Send a push notification
     */
    async sendNotificationRaw(requestParameters: SendNotificationOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['sendNotificationRequest'] == null) {
            throw new runtime.RequiredError(
                'sendNotificationRequest',
                'Required parameter "sendNotificationRequest" was null or undefined when calling sendNotification().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/notifications/send`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SendNotificationRequestToJSON(requestParameters['sendNotificationRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Send a push notification
     */
    async sendNotification(requestParameters: SendNotificationOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.sendNotificationRaw(requestParameters, initOverrides);
    }

    /**
     * Send a test push notification (for development only)
     */
    async testNotificationRaw(requestParameters: TestNotificationOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['testNotificationRequest'] == null) {
            throw new runtime.RequiredError(
                'testNotificationRequest',
                'Required parameter "testNotificationRequest" was null or undefined when calling testNotification().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/test-notification`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TestNotificationRequestToJSON(requestParameters['testNotificationRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Send a test push notification (for development only)
     */
    async testNotification(requestParameters: TestNotificationOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.testNotificationRaw(requestParameters, initOverrides);
    }

}
