/* tslint:disable */
/* eslint-disable */
/**
 * My App
 * This is an awesome app!
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BindPushTokensToUserRequest,
  RegisterPushTokenRequest,
} from '../models/index';
import {
    BindPushTokensToUserRequestFromJSON,
    BindPushTokensToUserRequestToJSON,
    RegisterPushTokenRequestFromJSON,
    RegisterPushTokenRequestToJSON,
} from '../models/index';

export interface BindPushTokensToUserOperationRequest {
    bindPushTokensToUserRequest: BindPushTokensToUserRequest;
}

export interface RegisterPushTokenOperationRequest {
    registerPushTokenRequest: RegisterPushTokenRequest;
}

/**
 * 
 */
export class PushTokenApi extends runtime.BaseAPI {

    /**
     * Bind anonymous push tokens to authenticated user
     */
    async bindPushTokensToUserRaw(requestParameters: BindPushTokensToUserOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['bindPushTokensToUserRequest'] == null) {
            throw new runtime.RequiredError(
                'bindPushTokensToUserRequest',
                'Required parameter "bindPushTokensToUserRequest" was null or undefined when calling bindPushTokensToUser().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/push-tokens/bind`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BindPushTokensToUserRequestToJSON(requestParameters['bindPushTokensToUserRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Bind anonymous push tokens to authenticated user
     */
    async bindPushTokensToUser(requestParameters: BindPushTokensToUserOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.bindPushTokensToUserRaw(requestParameters, initOverrides);
    }

    /**
     * Register or update a push token for notifications
     */
    async registerPushTokenRaw(requestParameters: RegisterPushTokenOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['registerPushTokenRequest'] == null) {
            throw new runtime.RequiredError(
                'registerPushTokenRequest',
                'Required parameter "registerPushTokenRequest" was null or undefined when calling registerPushToken().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/push-tokens`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RegisterPushTokenRequestToJSON(requestParameters['registerPushTokenRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Register or update a push token for notifications
     */
    async registerPushToken(requestParameters: RegisterPushTokenOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.registerPushTokenRaw(requestParameters, initOverrides);
    }

}
