/* tslint:disable */
/* eslint-disable */
/**
 * My App
 * This is an awesome app!
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AdvertisementWithFiltersResponse,
  GetSimpleAutoCollectionPagination200Response,
  SimpleAutoBrand,
  SimpleAutoGeneration,
  SimpleAutoModel,
} from '../models/index';
import {
    AdvertisementWithFiltersResponseFromJSON,
    AdvertisementWithFiltersResponseToJSON,
    GetSimpleAutoCollectionPagination200ResponseFromJSON,
    GetSimpleAutoCollectionPagination200ResponseToJSON,
    SimpleAutoBrandFromJSON,
    SimpleAutoBrandToJSON,
    SimpleAutoGenerationFromJSON,
    SimpleAutoGenerationToJSON,
    SimpleAutoModelFromJSON,
    SimpleAutoModelToJSON,
} from '../models/index';

export interface GetSimpleAutoAdvertisementRequest {
    advertismentId: number;
    locale: GetSimpleAutoAdvertisementLocaleEnum;
}

export interface GetSimpleAutoCollectionPaginationRequest {
    page: string;
    limit: string;
    b?: { [key: string]: any; };
    f?: { [key: string]: any; };
    sort?: { [key: string]: any; };
}

export interface GetSimpleAutoGenerationsRequest {
    brandId: string;
    modelId: string;
}

export interface GetSimpleAutoModelsRequest {
    brandId: string;
}

/**
 * 
 */
export class SimpleAutoApi extends runtime.BaseAPI {

    /**
     */
    async createSimpleAutoAdvertisementRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/simple-auto/advertisments`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async createSimpleAutoAdvertisement(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.createSimpleAutoAdvertisementRaw(initOverrides);
    }

    /**
     * Get single advertisement by ID
     * Get single advertisement
     */
    async getSimpleAutoAdvertisementRaw(requestParameters: GetSimpleAutoAdvertisementRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdvertisementWithFiltersResponse>> {
        if (requestParameters['advertismentId'] == null) {
            throw new runtime.RequiredError(
                'advertismentId',
                'Required parameter "advertismentId" was null or undefined when calling getSimpleAutoAdvertisement().'
            );
        }

        if (requestParameters['locale'] == null) {
            throw new runtime.RequiredError(
                'locale',
                'Required parameter "locale" was null or undefined when calling getSimpleAutoAdvertisement().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/simple-auto/advertisments/{advertismentId}/{_locale}`;
        urlPath = urlPath.replace(`{${"advertismentId"}}`, encodeURIComponent(String(requestParameters['advertismentId'])));
        urlPath = urlPath.replace(`{${"_locale"}}`, encodeURIComponent(String(requestParameters['locale'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AdvertisementWithFiltersResponseFromJSON(jsonValue));
    }

    /**
     * Get single advertisement by ID
     * Get single advertisement
     */
    async getSimpleAutoAdvertisement(requestParameters: GetSimpleAutoAdvertisementRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdvertisementWithFiltersResponse> {
        const response = await this.getSimpleAutoAdvertisementRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getSimpleAutoBrandsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SimpleAutoBrand>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/simple-auto/brands`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SimpleAutoBrandFromJSON));
    }

    /**
     */
    async getSimpleAutoBrands(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SimpleAutoBrand>> {
        const response = await this.getSimpleAutoBrandsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get simple auto collection pagination
     * Get simple auto collection pagination
     */
    async getSimpleAutoCollectionPaginationRaw(requestParameters: GetSimpleAutoCollectionPaginationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetSimpleAutoCollectionPagination200Response>> {
        if (requestParameters['page'] == null) {
            throw new runtime.RequiredError(
                'page',
                'Required parameter "page" was null or undefined when calling getSimpleAutoCollectionPagination().'
            );
        }

        if (requestParameters['limit'] == null) {
            throw new runtime.RequiredError(
                'limit',
                'Required parameter "limit" was null or undefined when calling getSimpleAutoCollectionPagination().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['b'] != null) {
            queryParameters['b'] = requestParameters['b'];
        }

        if (requestParameters['f'] != null) {
            queryParameters['f'] = requestParameters['f'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/simple-auto/advertisments`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetSimpleAutoCollectionPagination200ResponseFromJSON(jsonValue));
    }

    /**
     * Get simple auto collection pagination
     * Get simple auto collection pagination
     */
    async getSimpleAutoCollectionPagination(requestParameters: GetSimpleAutoCollectionPaginationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetSimpleAutoCollectionPagination200Response> {
        const response = await this.getSimpleAutoCollectionPaginationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getSimpleAutoGenerationsRaw(requestParameters: GetSimpleAutoGenerationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SimpleAutoGeneration>>> {
        if (requestParameters['brandId'] == null) {
            throw new runtime.RequiredError(
                'brandId',
                'Required parameter "brandId" was null or undefined when calling getSimpleAutoGenerations().'
            );
        }

        if (requestParameters['modelId'] == null) {
            throw new runtime.RequiredError(
                'modelId',
                'Required parameter "modelId" was null or undefined when calling getSimpleAutoGenerations().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/simple-auto/brands/{brandId}/models/{modelId}/generations`;
        urlPath = urlPath.replace(`{${"brandId"}}`, encodeURIComponent(String(requestParameters['brandId'])));
        urlPath = urlPath.replace(`{${"modelId"}}`, encodeURIComponent(String(requestParameters['modelId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SimpleAutoGenerationFromJSON));
    }

    /**
     */
    async getSimpleAutoGenerations(requestParameters: GetSimpleAutoGenerationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SimpleAutoGeneration>> {
        const response = await this.getSimpleAutoGenerationsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getSimpleAutoModelsRaw(requestParameters: GetSimpleAutoModelsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SimpleAutoModel>>> {
        if (requestParameters['brandId'] == null) {
            throw new runtime.RequiredError(
                'brandId',
                'Required parameter "brandId" was null or undefined when calling getSimpleAutoModels().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/simple-auto/brands/{brandId}/models`;
        urlPath = urlPath.replace(`{${"brandId"}}`, encodeURIComponent(String(requestParameters['brandId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SimpleAutoModelFromJSON));
    }

    /**
     */
    async getSimpleAutoModels(requestParameters: GetSimpleAutoModelsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SimpleAutoModel>> {
        const response = await this.getSimpleAutoModelsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const GetSimpleAutoAdvertisementLocaleEnum = {
    En: 'en',
    Ro: 'ro',
    Ru: 'ru',
    Uk: 'uk'
} as const;
export type GetSimpleAutoAdvertisementLocaleEnum = typeof GetSimpleAutoAdvertisementLocaleEnum[keyof typeof GetSimpleAutoAdvertisementLocaleEnum];
