/* tslint:disable */
/* eslint-disable */
/**
 * My App
 * This is an awesome app!
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GetAppSimpleautocontextPresentationBrandgetcollectionGetbrands200ResponseInner,
  GetAppSimpleautocontextPresentationSimpleautogetcollectionGetcollectionbyfilters200ResponseInner,
  GetAppSimpleautocontextPresentationSimpleautogetoneGetcollectionbyfilters200Response,
  PostAppSimpleautocontextPresentationSimpleautocreateCreateRequest,
} from '../models/index';
import {
    GetAppSimpleautocontextPresentationBrandgetcollectionGetbrands200ResponseInnerFromJSON,
    GetAppSimpleautocontextPresentationBrandgetcollectionGetbrands200ResponseInnerToJSON,
    GetAppSimpleautocontextPresentationSimpleautogetcollectionGetcollectionbyfilters200ResponseInnerFromJSON,
    GetAppSimpleautocontextPresentationSimpleautogetcollectionGetcollectionbyfilters200ResponseInnerToJSON,
    GetAppSimpleautocontextPresentationSimpleautogetoneGetcollectionbyfilters200ResponseFromJSON,
    GetAppSimpleautocontextPresentationSimpleautogetoneGetcollectionbyfilters200ResponseToJSON,
    PostAppSimpleautocontextPresentationSimpleautocreateCreateRequestFromJSON,
    PostAppSimpleautocontextPresentationSimpleautocreateCreateRequestToJSON,
} from '../models/index';

export interface GetAppSimpleautocontextPresentationModelgetcollectionGetcollectionbyfiltersRequest {
    brandId: string;
}

export interface GetAppSimpleautocontextPresentationSimpleautogetcollectionGetcollectionbyfiltersRequest {
    brand?: string;
    model?: string;
    releaseYear?: number;
    price?: string;
    filterParameters?: Array<string>;
}

export interface GetAppSimpleautocontextPresentationSimpleautogetoneGetcollectionbyfiltersRequest {
    advertismentId: string;
}

export interface PostAppSimpleautocontextPresentationSimpleautocreateCreateOperationRequest {
    postAppSimpleautocontextPresentationSimpleautocreateCreateRequest: PostAppSimpleautocontextPresentationSimpleautocreateCreateRequest;
}

/**
 * 
 */
export class SimpleAutoApi extends runtime.BaseAPI {

    /**
     */
    async getAppSimpleautocontextPresentationBrandgetcollectionGetbrandsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<GetAppSimpleautocontextPresentationBrandgetcollectionGetbrands200ResponseInner>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/simple-auto/brands`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(GetAppSimpleautocontextPresentationBrandgetcollectionGetbrands200ResponseInnerFromJSON));
    }

    /**
     */
    async getAppSimpleautocontextPresentationBrandgetcollectionGetbrands(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<GetAppSimpleautocontextPresentationBrandgetcollectionGetbrands200ResponseInner>> {
        const response = await this.getAppSimpleautocontextPresentationBrandgetcollectionGetbrandsRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async getAppSimpleautocontextPresentationModelgetcollectionGetcollectionbyfiltersRaw(requestParameters: GetAppSimpleautocontextPresentationModelgetcollectionGetcollectionbyfiltersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<GetAppSimpleautocontextPresentationBrandgetcollectionGetbrands200ResponseInner>>> {
        if (requestParameters['brandId'] == null) {
            throw new runtime.RequiredError(
                'brandId',
                'Required parameter "brandId" was null or undefined when calling getAppSimpleautocontextPresentationModelgetcollectionGetcollectionbyfilters().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/simple-auto/brands/{brandId}/models`;
        urlPath = urlPath.replace(`{${"brandId"}}`, encodeURIComponent(String(requestParameters['brandId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(GetAppSimpleautocontextPresentationBrandgetcollectionGetbrands200ResponseInnerFromJSON));
    }

    /**
     */
    async getAppSimpleautocontextPresentationModelgetcollectionGetcollectionbyfilters(requestParameters: GetAppSimpleautocontextPresentationModelgetcollectionGetcollectionbyfiltersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<GetAppSimpleautocontextPresentationBrandgetcollectionGetbrands200ResponseInner>> {
        const response = await this.getAppSimpleautocontextPresentationModelgetcollectionGetcollectionbyfiltersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getAppSimpleautocontextPresentationSimpleautogetcollectionGetcollectionbyfiltersRaw(requestParameters: GetAppSimpleautocontextPresentationSimpleautogetcollectionGetcollectionbyfiltersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<GetAppSimpleautocontextPresentationSimpleautogetcollectionGetcollectionbyfilters200ResponseInner>>> {
        const queryParameters: any = {};

        if (requestParameters['brand'] != null) {
            queryParameters['brand'] = requestParameters['brand'];
        }

        if (requestParameters['model'] != null) {
            queryParameters['model'] = requestParameters['model'];
        }

        if (requestParameters['releaseYear'] != null) {
            queryParameters['releaseYear'] = requestParameters['releaseYear'];
        }

        if (requestParameters['price'] != null) {
            queryParameters['price'] = requestParameters['price'];
        }

        if (requestParameters['filterParameters'] != null) {
            queryParameters['filterParameters'] = requestParameters['filterParameters'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/simple-auto/advertisments`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(GetAppSimpleautocontextPresentationSimpleautogetcollectionGetcollectionbyfilters200ResponseInnerFromJSON));
    }

    /**
     */
    async getAppSimpleautocontextPresentationSimpleautogetcollectionGetcollectionbyfilters(requestParameters: GetAppSimpleautocontextPresentationSimpleautogetcollectionGetcollectionbyfiltersRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<GetAppSimpleautocontextPresentationSimpleautogetcollectionGetcollectionbyfilters200ResponseInner>> {
        const response = await this.getAppSimpleautocontextPresentationSimpleautogetcollectionGetcollectionbyfiltersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getAppSimpleautocontextPresentationSimpleautogetoneGetcollectionbyfiltersRaw(requestParameters: GetAppSimpleautocontextPresentationSimpleautogetoneGetcollectionbyfiltersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetAppSimpleautocontextPresentationSimpleautogetoneGetcollectionbyfilters200Response>> {
        if (requestParameters['advertismentId'] == null) {
            throw new runtime.RequiredError(
                'advertismentId',
                'Required parameter "advertismentId" was null or undefined when calling getAppSimpleautocontextPresentationSimpleautogetoneGetcollectionbyfilters().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/simple-auto/advertisments/{advertismentId}`;
        urlPath = urlPath.replace(`{${"advertismentId"}}`, encodeURIComponent(String(requestParameters['advertismentId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetAppSimpleautocontextPresentationSimpleautogetoneGetcollectionbyfilters200ResponseFromJSON(jsonValue));
    }

    /**
     */
    async getAppSimpleautocontextPresentationSimpleautogetoneGetcollectionbyfilters(requestParameters: GetAppSimpleautocontextPresentationSimpleautogetoneGetcollectionbyfiltersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetAppSimpleautocontextPresentationSimpleautogetoneGetcollectionbyfilters200Response> {
        const response = await this.getAppSimpleautocontextPresentationSimpleautogetoneGetcollectionbyfiltersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async postAppSimpleautocontextPresentationSimpleautocreateCreateRaw(requestParameters: PostAppSimpleautocontextPresentationSimpleautocreateCreateOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['postAppSimpleautocontextPresentationSimpleautocreateCreateRequest'] == null) {
            throw new runtime.RequiredError(
                'postAppSimpleautocontextPresentationSimpleautocreateCreateRequest',
                'Required parameter "postAppSimpleautocontextPresentationSimpleautocreateCreateRequest" was null or undefined when calling postAppSimpleautocontextPresentationSimpleautocreateCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/simple-auto/advertisments`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PostAppSimpleautocontextPresentationSimpleautocreateCreateRequestToJSON(requestParameters['postAppSimpleautocontextPresentationSimpleautocreateCreateRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async postAppSimpleautocontextPresentationSimpleautocreateCreate(requestParameters: PostAppSimpleautocontextPresentationSimpleautocreateCreateOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.postAppSimpleautocontextPresentationSimpleautocreateCreateRaw(requestParameters, initOverrides);
    }

}
