/* tslint:disable */
/* eslint-disable */
/**
 * My App
 * This is an awesome app!
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GetAppSpecautocontextPresentationBrandgetcollectionGetbrands200ResponseInner,
  GetAppSpecautocontextPresentationModelgetcollectionGetcollectionbyfilters200ResponseInner,
  GetAppSpecautocontextPresentationSpecautogetcollectionGetcollectionbyfilters200ResponseInner,
  PostAppSpecautocontextPresentationSpecautocreateCreateRequest,
} from '../models/index';
import {
    GetAppSpecautocontextPresentationBrandgetcollectionGetbrands200ResponseInnerFromJSON,
    GetAppSpecautocontextPresentationBrandgetcollectionGetbrands200ResponseInnerToJSON,
    GetAppSpecautocontextPresentationModelgetcollectionGetcollectionbyfilters200ResponseInnerFromJSON,
    GetAppSpecautocontextPresentationModelgetcollectionGetcollectionbyfilters200ResponseInnerToJSON,
    GetAppSpecautocontextPresentationSpecautogetcollectionGetcollectionbyfilters200ResponseInnerFromJSON,
    GetAppSpecautocontextPresentationSpecautogetcollectionGetcollectionbyfilters200ResponseInnerToJSON,
    PostAppSpecautocontextPresentationSpecautocreateCreateRequestFromJSON,
    PostAppSpecautocontextPresentationSpecautocreateCreateRequestToJSON,
} from '../models/index';

export interface GetAppSpecautocontextPresentationModelgetcollectionGetcollectionbyfiltersRequest {
    brandId: string;
}

export interface GetAppSpecautocontextPresentationSpecautogetcollectionGetcollectionbyfiltersRequest {
    brand?: string;
    model?: string;
    releaseYear?: number;
    price?: string;
    additionalFilters?: Array<string>;
}

export interface GetAppSpecautocontextPresentationSpecautogetoneGetcollectionbyfiltersRequest {
    advertismentId: string;
}

export interface PostAppSpecautocontextPresentationSpecautocreateCreateOperationRequest {
    postAppSpecautocontextPresentationSpecautocreateCreateRequest: PostAppSpecautocontextPresentationSpecautocreateCreateRequest;
}

/**
 * 
 */
export class SpecAutoApi extends runtime.BaseAPI {

    /**
     */
    async getAppSpecautocontextPresentationBrandgetcollectionGetbrandsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<GetAppSpecautocontextPresentationBrandgetcollectionGetbrands200ResponseInner>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/spec-auto/brands`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(GetAppSpecautocontextPresentationBrandgetcollectionGetbrands200ResponseInnerFromJSON));
    }

    /**
     */
    async getAppSpecautocontextPresentationBrandgetcollectionGetbrands(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<GetAppSpecautocontextPresentationBrandgetcollectionGetbrands200ResponseInner>> {
        const response = await this.getAppSpecautocontextPresentationBrandgetcollectionGetbrandsRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async getAppSpecautocontextPresentationModelgetcollectionGetcollectionbyfiltersRaw(requestParameters: GetAppSpecautocontextPresentationModelgetcollectionGetcollectionbyfiltersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<GetAppSpecautocontextPresentationModelgetcollectionGetcollectionbyfilters200ResponseInner>>> {
        if (requestParameters['brandId'] == null) {
            throw new runtime.RequiredError(
                'brandId',
                'Required parameter "brandId" was null or undefined when calling getAppSpecautocontextPresentationModelgetcollectionGetcollectionbyfilters().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/spec-auto/brands/{brandId}/models`;
        urlPath = urlPath.replace(`{${"brandId"}}`, encodeURIComponent(String(requestParameters['brandId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(GetAppSpecautocontextPresentationModelgetcollectionGetcollectionbyfilters200ResponseInnerFromJSON));
    }

    /**
     */
    async getAppSpecautocontextPresentationModelgetcollectionGetcollectionbyfilters(requestParameters: GetAppSpecautocontextPresentationModelgetcollectionGetcollectionbyfiltersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<GetAppSpecautocontextPresentationModelgetcollectionGetcollectionbyfilters200ResponseInner>> {
        const response = await this.getAppSpecautocontextPresentationModelgetcollectionGetcollectionbyfiltersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getAppSpecautocontextPresentationSpecautogetcollectionGetcollectionbyfiltersRaw(requestParameters: GetAppSpecautocontextPresentationSpecautogetcollectionGetcollectionbyfiltersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<GetAppSpecautocontextPresentationSpecautogetcollectionGetcollectionbyfilters200ResponseInner>>> {
        const queryParameters: any = {};

        if (requestParameters['brand'] != null) {
            queryParameters['brand'] = requestParameters['brand'];
        }

        if (requestParameters['model'] != null) {
            queryParameters['model'] = requestParameters['model'];
        }

        if (requestParameters['releaseYear'] != null) {
            queryParameters['releaseYear'] = requestParameters['releaseYear'];
        }

        if (requestParameters['price'] != null) {
            queryParameters['price'] = requestParameters['price'];
        }

        if (requestParameters['additionalFilters'] != null) {
            queryParameters['additionalFilters'] = requestParameters['additionalFilters'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/spec-auto/advertisments`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(GetAppSpecautocontextPresentationSpecautogetcollectionGetcollectionbyfilters200ResponseInnerFromJSON));
    }

    /**
     */
    async getAppSpecautocontextPresentationSpecautogetcollectionGetcollectionbyfilters(requestParameters: GetAppSpecautocontextPresentationSpecautogetcollectionGetcollectionbyfiltersRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<GetAppSpecautocontextPresentationSpecautogetcollectionGetcollectionbyfilters200ResponseInner>> {
        const response = await this.getAppSpecautocontextPresentationSpecautogetcollectionGetcollectionbyfiltersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getAppSpecautocontextPresentationSpecautogetoneGetcollectionbyfiltersRaw(requestParameters: GetAppSpecautocontextPresentationSpecautogetoneGetcollectionbyfiltersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetAppSpecautocontextPresentationSpecautogetcollectionGetcollectionbyfilters200ResponseInner>> {
        if (requestParameters['advertismentId'] == null) {
            throw new runtime.RequiredError(
                'advertismentId',
                'Required parameter "advertismentId" was null or undefined when calling getAppSpecautocontextPresentationSpecautogetoneGetcollectionbyfilters().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/spec-auto/advertisments/{advertismentId}`;
        urlPath = urlPath.replace(`{${"advertismentId"}}`, encodeURIComponent(String(requestParameters['advertismentId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetAppSpecautocontextPresentationSpecautogetcollectionGetcollectionbyfilters200ResponseInnerFromJSON(jsonValue));
    }

    /**
     */
    async getAppSpecautocontextPresentationSpecautogetoneGetcollectionbyfilters(requestParameters: GetAppSpecautocontextPresentationSpecautogetoneGetcollectionbyfiltersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetAppSpecautocontextPresentationSpecautogetcollectionGetcollectionbyfilters200ResponseInner> {
        const response = await this.getAppSpecautocontextPresentationSpecautogetoneGetcollectionbyfiltersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async postAppSpecautocontextPresentationSpecautocreateCreateRaw(requestParameters: PostAppSpecautocontextPresentationSpecautocreateCreateOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['postAppSpecautocontextPresentationSpecautocreateCreateRequest'] == null) {
            throw new runtime.RequiredError(
                'postAppSpecautocontextPresentationSpecautocreateCreateRequest',
                'Required parameter "postAppSpecautocontextPresentationSpecautocreateCreateRequest" was null or undefined when calling postAppSpecautocontextPresentationSpecautocreateCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/spec-auto/advertisments`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PostAppSpecautocontextPresentationSpecautocreateCreateRequestToJSON(requestParameters['postAppSpecautocontextPresentationSpecautocreateCreateRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async postAppSpecautocontextPresentationSpecautocreateCreate(requestParameters: PostAppSpecautocontextPresentationSpecautocreateCreateOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.postAppSpecautocontextPresentationSpecautocreateCreateRaw(requestParameters, initOverrides);
    }

}
