/* tslint:disable */
/* eslint-disable */
/**
 * My App
 * This is an awesome app!
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AddUserFavorite201Response,
  AddUserFavoriteRequest,
  GetUserFavorites200Response,
} from '../models/index';
import {
    AddUserFavorite201ResponseFromJSON,
    AddUserFavorite201ResponseToJSON,
    AddUserFavoriteRequestFromJSON,
    AddUserFavoriteRequestToJSON,
    GetUserFavorites200ResponseFromJSON,
    GetUserFavorites200ResponseToJSON,
} from '../models/index';

export interface AddUserFavoriteOperationRequest {
    addUserFavoriteRequest: AddUserFavoriteRequest;
}

export interface DeleteUserFavoriteRequest {
    id: number;
}

export interface GetUserFavoritesRequest {
    page?: number;
    limit?: number;
}

/**
 * 
 */
export class UserFavoriteApi extends runtime.BaseAPI {

    /**
     */
    async addUserFavoriteRaw(requestParameters: AddUserFavoriteOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AddUserFavorite201Response>> {
        if (requestParameters['addUserFavoriteRequest'] == null) {
            throw new runtime.RequiredError(
                'addUserFavoriteRequest',
                'Required parameter "addUserFavoriteRequest" was null or undefined when calling addUserFavorite().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/users/favorites`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AddUserFavoriteRequestToJSON(requestParameters['addUserFavoriteRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AddUserFavorite201ResponseFromJSON(jsonValue));
    }

    /**
     */
    async addUserFavorite(requestParameters: AddUserFavoriteOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AddUserFavorite201Response> {
        const response = await this.addUserFavoriteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete a specific favorite by ID. Only the owner can delete their favorites.
     * Delete a user favorite
     */
    async deleteUserFavoriteRaw(requestParameters: DeleteUserFavoriteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AddUserFavorite201Response>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteUserFavorite().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/users/favorites/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AddUserFavorite201ResponseFromJSON(jsonValue));
    }

    /**
     * Delete a specific favorite by ID. Only the owner can delete their favorites.
     * Delete a user favorite
     */
    async deleteUserFavorite(requestParameters: DeleteUserFavoriteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AddUserFavorite201Response> {
        const response = await this.deleteUserFavoriteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get user favorites collection with pagination
     * Get user favorites collection with pagination
     */
    async getUserFavoritesRaw(requestParameters: GetUserFavoritesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetUserFavorites200Response>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/users/favorites`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetUserFavorites200ResponseFromJSON(jsonValue));
    }

    /**
     * Get user favorites collection with pagination
     * Get user favorites collection with pagination
     */
    async getUserFavorites(requestParameters: GetUserFavoritesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetUserFavorites200Response> {
        const response = await this.getUserFavoritesRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
