/* tslint:disable */
/* eslint-disable */
/**
 * My App
 * This is an awesome app!
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GetUserAdvertisements200Response,
} from '../models/index';
import {
    GetUserAdvertisements200ResponseFromJSON,
    GetUserAdvertisements200ResponseToJSON,
} from '../models/index';

export interface GetUserAdvertisementsRequest {
    page?: number;
    limit?: number;
}

/**
 * 
 */
export class UserAdvertisementApi extends runtime.BaseAPI {

    /**
     * Get user advertisements collection with pagination
     * Get user advertisements collection with pagination
     */
    async getUserAdvertisementsRaw(requestParameters: GetUserAdvertisementsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetUserAdvertisements200Response>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/users/advertisements`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetUserAdvertisements200ResponseFromJSON(jsonValue));
    }

    /**
     * Get user advertisements collection with pagination
     * Get user advertisements collection with pagination
     */
    async getUserAdvertisements(requestParameters: GetUserAdvertisementsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetUserAdvertisements200Response> {
        const response = await this.getUserAdvertisementsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
