/* tslint:disable */
/* eslint-disable */
/**
 * My App
 * This is an awesome app!
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateUserSubscriptionFilterRequest,
  GetUserSubscriptionFilter200Response,
  UserSubscriptionFilter,
} from '../models/index';
import {
    CreateUserSubscriptionFilterRequestFromJSON,
    CreateUserSubscriptionFilterRequestToJSON,
    GetUserSubscriptionFilter200ResponseFromJSON,
    GetUserSubscriptionFilter200ResponseToJSON,
    UserSubscriptionFilterFromJSON,
    UserSubscriptionFilterToJSON,
} from '../models/index';

export interface CreateUserSubscriptionFilterOperationRequest {
    createUserSubscriptionFilterRequest: CreateUserSubscriptionFilterRequest;
}

export interface GetUserSubscriptionFilterRequest {
    subscriptionFilterId: string;
}

/**
 * 
 */
export class UserSubscriptionFilterApi extends runtime.BaseAPI {

    /**
     */
    async createUserSubscriptionFilterRaw(requestParameters: CreateUserSubscriptionFilterOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['createUserSubscriptionFilterRequest'] == null) {
            throw new runtime.RequiredError(
                'createUserSubscriptionFilterRequest',
                'Required parameter "createUserSubscriptionFilterRequest" was null or undefined when calling createUserSubscriptionFilter().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/users/subscription-filters`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateUserSubscriptionFilterRequestToJSON(requestParameters['createUserSubscriptionFilterRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async createUserSubscriptionFilter(requestParameters: CreateUserSubscriptionFilterOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.createUserSubscriptionFilterRaw(requestParameters, initOverrides);
    }

    /**
     */
    async getUserSubscriptionFilterRaw(requestParameters: GetUserSubscriptionFilterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetUserSubscriptionFilter200Response>> {
        if (requestParameters['subscriptionFilterId'] == null) {
            throw new runtime.RequiredError(
                'subscriptionFilterId',
                'Required parameter "subscriptionFilterId" was null or undefined when calling getUserSubscriptionFilter().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/users/subscription-filters/{subscriptionFilterId}`;
        urlPath = urlPath.replace(`{${"subscriptionFilterId"}}`, encodeURIComponent(String(requestParameters['subscriptionFilterId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetUserSubscriptionFilter200ResponseFromJSON(jsonValue));
    }

    /**
     */
    async getUserSubscriptionFilter(requestParameters: GetUserSubscriptionFilterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetUserSubscriptionFilter200Response> {
        const response = await this.getUserSubscriptionFilterRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getUserSubscriptionFiltersRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<UserSubscriptionFilter>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/users/subscription-filters`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(UserSubscriptionFilterFromJSON));
    }

    /**
     */
    async getUserSubscriptionFilters(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<UserSubscriptionFilter>> {
        const response = await this.getUserSubscriptionFiltersRaw(initOverrides);
        return await response.value();
    }

}
