/* tslint:disable */
/* eslint-disable */
/**
 * My App
 * This is an awesome app!
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

export interface PostAppUserdomainPresentationUserfavoriteUserfavoritedeleteDeleteuserfavoriteRequest {
    productSlug: string;
}

/**
 * 
 */
export class UserFavoriteApi extends runtime.BaseAPI {

    /**
     */
    async postAppUserdomainPresentationUserfavoriteUserfavoritedeleteDeleteuserfavoriteRaw(requestParameters: PostAppUserdomainPresentationUserfavoriteUserfavoritedeleteDeleteuserfavoriteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['productSlug'] == null) {
            throw new runtime.RequiredError(
                'productSlug',
                'Required parameter "productSlug" was null or undefined when calling postAppUserdomainPresentationUserfavoriteUserfavoritedeleteDeleteuserfavorite().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/products/{productSlug}/services`;
        urlPath = urlPath.replace(`{${"productSlug"}}`, encodeURIComponent(String(requestParameters['productSlug'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async postAppUserdomainPresentationUserfavoriteUserfavoritedeleteDeleteuserfavorite(requestParameters: PostAppUserdomainPresentationUserfavoriteUserfavoritedeleteDeleteuserfavoriteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.postAppUserdomainPresentationUserfavoriteUserfavoritedeleteDeleteuserfavoriteRaw(requestParameters, initOverrides);
    }

}
