/* tslint:disable */
/* eslint-disable */
/**
 * My App
 * This is an awesome app!
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddUserFavorite201Response
 */
export interface AddUserFavorite201Response {
    /**
     * 
     * @type {string}
     * @memberof AddUserFavorite201Response
     */
    message?: string;
    /**
     * 
     * @type {boolean}
     * @memberof AddUserFavorite201Response
     */
    success?: boolean;
}

/**
 * Check if a given object implements the AddUserFavorite201Response interface.
 */
export function instanceOfAddUserFavorite201Response(value: object): value is AddUserFavorite201Response {
    return true;
}

export function AddUserFavorite201ResponseFromJSON(json: any): AddUserFavorite201Response {
    return AddUserFavorite201ResponseFromJSONTyped(json, false);
}

export function AddUserFavorite201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddUserFavorite201Response {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'success': json['success'] == null ? undefined : json['success'],
    };
}

export function AddUserFavorite201ResponseToJSON(json: any): AddUserFavorite201Response {
    return AddUserFavorite201ResponseToJSONTyped(json, false);
}

export function AddUserFavorite201ResponseToJSONTyped(value?: AddUserFavorite201Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'success': value['success'],
    };
}

