/* tslint:disable */
/* eslint-disable */
/**
 * My App
 * This is an awesome app!
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddUserFavoriteRequest
 */
export interface AddUserFavoriteRequest {
    /**
     * ID of the advertisement to add to favorites
     * @type {number}
     * @memberof AddUserFavoriteRequest
     */
    advertisementId: number;
}

/**
 * Check if a given object implements the AddUserFavoriteRequest interface.
 */
export function instanceOfAddUserFavoriteRequest(value: object): value is AddUserFavoriteRequest {
    if (!('advertisementId' in value) || value['advertisementId'] === undefined) return false;
    return true;
}

export function AddUserFavoriteRequestFromJSON(json: any): AddUserFavoriteRequest {
    return AddUserFavoriteRequestFromJSONTyped(json, false);
}

export function AddUserFavoriteRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddUserFavoriteRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'advertisementId': json['advertisementId'],
    };
}

export function AddUserFavoriteRequestToJSON(json: any): AddUserFavoriteRequest {
    return AddUserFavoriteRequestToJSONTyped(json, false);
}

export function AddUserFavoriteRequestToJSONTyped(value?: AddUserFavoriteRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'advertisementId': value['advertisementId'],
    };
}

