/* tslint:disable */
/* eslint-disable */
/**
 * My App
 * This is an awesome app!
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Advertisement item response
 * @export
 * @interface AdvertisementItemResponse
 */
export interface AdvertisementItemResponse {
    /**
     * 
     * @type {number}
     * @memberof AdvertisementItemResponse
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof AdvertisementItemResponse
     */
    brand: string;
    /**
     * 
     * @type {string}
     * @memberof AdvertisementItemResponse
     */
    model: string;
    /**
     * 
     * @type {string}
     * @memberof AdvertisementItemResponse
     */
    price: string;
    /**
     * 
     * @type {string}
     * @memberof AdvertisementItemResponse
     */
    currency: string;
    /**
     * 
     * @type {number}
     * @memberof AdvertisementItemResponse
     */
    releaseYear: number;
    /**
     * 
     * @type {string}
     * @memberof AdvertisementItemResponse
     */
    region: string;
    /**
     * 
     * @type {Date}
     * @memberof AdvertisementItemResponse
     */
    createdAt: Date;
    /**
     * 
     * @type {Array<string>}
     * @memberof AdvertisementItemResponse
     */
    images?: Array<string>;
}

/**
 * Check if a given object implements the AdvertisementItemResponse interface.
 */
export function instanceOfAdvertisementItemResponse(value: object): value is AdvertisementItemResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('brand' in value) || value['brand'] === undefined) return false;
    if (!('model' in value) || value['model'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('releaseYear' in value) || value['releaseYear'] === undefined) return false;
    if (!('region' in value) || value['region'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function AdvertisementItemResponseFromJSON(json: any): AdvertisementItemResponse {
    return AdvertisementItemResponseFromJSONTyped(json, false);
}

export function AdvertisementItemResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdvertisementItemResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'brand': json['brand'],
        'model': json['model'],
        'price': json['price'],
        'currency': json['currency'],
        'releaseYear': json['releaseYear'],
        'region': json['region'],
        'createdAt': (new Date(json['createdAt'])),
        'images': json['images'] == null ? undefined : json['images'],
    };
}

export function AdvertisementItemResponseToJSON(json: any): AdvertisementItemResponse {
    return AdvertisementItemResponseToJSONTyped(json, false);
}

export function AdvertisementItemResponseToJSONTyped(value?: AdvertisementItemResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'brand': value['brand'],
        'model': value['model'],
        'price': value['price'],
        'currency': value['currency'],
        'releaseYear': value['releaseYear'],
        'region': value['region'],
        'createdAt': value['createdAt'].toISOString(),
        'images': value['images'],
    };
}

