/* tslint:disable */
/* eslint-disable */
/**
 * My App
 * This is an awesome app!
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdvertisementFilterParameterResponse } from './AdvertisementFilterParameterResponse';
import {
    AdvertisementFilterParameterResponseFromJSON,
    AdvertisementFilterParameterResponseFromJSONTyped,
    AdvertisementFilterParameterResponseToJSON,
    AdvertisementFilterParameterResponseToJSONTyped,
} from './AdvertisementFilterParameterResponse';

/**
 * Advertisement with filter parameters response
 * @export
 * @interface AdvertisementWithFiltersResponse
 */
export interface AdvertisementWithFiltersResponse {
    /**
     * 
     * @type {Array<AdvertisementFilterParameterResponse>}
     * @memberof AdvertisementWithFiltersResponse
     */
    filterParameters?: Array<AdvertisementFilterParameterResponse>;
    /**
     * 
     * @type {number}
     * @memberof AdvertisementWithFiltersResponse
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof AdvertisementWithFiltersResponse
     */
    brand: string;
    /**
     * 
     * @type {string}
     * @memberof AdvertisementWithFiltersResponse
     */
    model: string;
    /**
     * 
     * @type {string}
     * @memberof AdvertisementWithFiltersResponse
     */
    price: string;
    /**
     * 
     * @type {string}
     * @memberof AdvertisementWithFiltersResponse
     */
    currency: string;
    /**
     * 
     * @type {number}
     * @memberof AdvertisementWithFiltersResponse
     */
    releaseYear: number;
    /**
     * 
     * @type {string}
     * @memberof AdvertisementWithFiltersResponse
     */
    region: string;
    /**
     * 
     * @type {Date}
     * @memberof AdvertisementWithFiltersResponse
     */
    createdAt: Date;
    /**
     * 
     * @type {Array<string>}
     * @memberof AdvertisementWithFiltersResponse
     */
    images?: Array<string>;
}

/**
 * Check if a given object implements the AdvertisementWithFiltersResponse interface.
 */
export function instanceOfAdvertisementWithFiltersResponse(value: object): value is AdvertisementWithFiltersResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('brand' in value) || value['brand'] === undefined) return false;
    if (!('model' in value) || value['model'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('releaseYear' in value) || value['releaseYear'] === undefined) return false;
    if (!('region' in value) || value['region'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function AdvertisementWithFiltersResponseFromJSON(json: any): AdvertisementWithFiltersResponse {
    return AdvertisementWithFiltersResponseFromJSONTyped(json, false);
}

export function AdvertisementWithFiltersResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdvertisementWithFiltersResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'filterParameters': json['filterParameters'] == null ? undefined : ((json['filterParameters'] as Array<any>).map(AdvertisementFilterParameterResponseFromJSON)),
        'id': json['id'],
        'brand': json['brand'],
        'model': json['model'],
        'price': json['price'],
        'currency': json['currency'],
        'releaseYear': json['releaseYear'],
        'region': json['region'],
        'createdAt': (new Date(json['createdAt'])),
        'images': json['images'] == null ? undefined : json['images'],
    };
}

export function AdvertisementWithFiltersResponseToJSON(json: any): AdvertisementWithFiltersResponse {
    return AdvertisementWithFiltersResponseToJSONTyped(json, false);
}

export function AdvertisementWithFiltersResponseToJSONTyped(value?: AdvertisementWithFiltersResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'filterParameters': value['filterParameters'] == null ? undefined : ((value['filterParameters'] as Array<any>).map(AdvertisementFilterParameterResponseToJSON)),
        'id': value['id'],
        'brand': value['brand'],
        'model': value['model'],
        'price': value['price'],
        'currency': value['currency'],
        'releaseYear': value['releaseYear'],
        'region': value['region'],
        'createdAt': value['createdAt'].toISOString(),
        'images': value['images'],
    };
}

