/* tslint:disable */
/* eslint-disable */
/**
 * My App
 * This is an awesome app!
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiAuthPostRequest
 */
export interface ApiAuthPostRequest {
    /**
     * 
     * @type {string}
     * @memberof ApiAuthPostRequest
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiAuthPostRequest
     */
    password?: string;
}

/**
 * Check if a given object implements the ApiAuthPostRequest interface.
 */
export function instanceOfApiAuthPostRequest(value: object): value is ApiAuthPostRequest {
    return true;
}

export function ApiAuthPostRequestFromJSON(json: any): ApiAuthPostRequest {
    return ApiAuthPostRequestFromJSONTyped(json, false);
}

export function ApiAuthPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiAuthPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'] == null ? undefined : json['email'],
        'password': json['password'] == null ? undefined : json['password'],
    };
}

export function ApiAuthPostRequestToJSON(json: any): ApiAuthPostRequest {
    return ApiAuthPostRequestToJSONTyped(json, false);
}

export function ApiAuthPostRequestToJSONTyped(value?: ApiAuthPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'password': value['password'],
    };
}

