/* tslint:disable */
/* eslint-disable */
/**
 * My App
 * This is an awesome app!
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiAuthPost200Response
 */
export interface ApiAuthPost200Response {
    /**
     * 
     * @type {Array<string>}
     * @memberof ApiAuthPost200Response
     */
    roles?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof ApiAuthPost200Response
     */
    token?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiAuthPost200Response
     */
    refreshToken?: string;
}

/**
 * Check if a given object implements the ApiAuthPost200Response interface.
 */
export function instanceOfApiAuthPost200Response(value: object): value is ApiAuthPost200Response {
    return true;
}

export function ApiAuthPost200ResponseFromJSON(json: any): ApiAuthPost200Response {
    return ApiAuthPost200ResponseFromJSONTyped(json, false);
}

export function ApiAuthPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiAuthPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'roles': json['roles'] == null ? undefined : json['roles'],
        'token': json['token'] == null ? undefined : json['token'],
        'refreshToken': json['refresh_token'] == null ? undefined : json['refresh_token'],
    };
}

export function ApiAuthPost200ResponseToJSON(json: any): ApiAuthPost200Response {
    return ApiAuthPost200ResponseToJSONTyped(json, false);
}

export function ApiAuthPost200ResponseToJSONTyped(value?: ApiAuthPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'roles': value['roles'],
        'token': value['token'],
        'refresh_token': value['refreshToken'],
    };
}

