/* tslint:disable */
/* eslint-disable */
/**
 * My App
 * This is an awesome app!
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BindPushTokensToUserRequest
 */
export interface BindPushTokensToUserRequest {
    /**
     * Array of device IDs to bind
     * @type {Array<string>}
     * @memberof BindPushTokensToUserRequest
     */
    deviceIds: Array<string>;
}

/**
 * Check if a given object implements the BindPushTokensToUserRequest interface.
 */
export function instanceOfBindPushTokensToUserRequest(value: object): value is BindPushTokensToUserRequest {
    if (!('deviceIds' in value) || value['deviceIds'] === undefined) return false;
    return true;
}

export function BindPushTokensToUserRequestFromJSON(json: any): BindPushTokensToUserRequest {
    return BindPushTokensToUserRequestFromJSONTyped(json, false);
}

export function BindPushTokensToUserRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BindPushTokensToUserRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'deviceIds': json['deviceIds'],
    };
}

export function BindPushTokensToUserRequestToJSON(json: any): BindPushTokensToUserRequest {
    return BindPushTokensToUserRequestToJSONTyped(json, false);
}

export function BindPushTokensToUserRequestToJSONTyped(value?: BindPushTokensToUserRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'deviceIds': value['deviceIds'],
    };
}

