/* tslint:disable */
/* eslint-disable */
/**
 * My App
 * This is an awesome app!
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateUserSubscriptionFilterRequest
 */
export interface CreateUserSubscriptionFilterRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateUserSubscriptionFilterRequest
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateUserSubscriptionFilterRequest
     */
    sourceType?: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof CreateUserSubscriptionFilterRequest
     */
    b?: { [key: string]: any; };
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof CreateUserSubscriptionFilterRequest
     */
    r?: { [key: string]: any; };
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof CreateUserSubscriptionFilterRequest
     */
    filterParameters?: { [key: string]: any; };
}

/**
 * Check if a given object implements the CreateUserSubscriptionFilterRequest interface.
 */
export function instanceOfCreateUserSubscriptionFilterRequest(value: object): value is CreateUserSubscriptionFilterRequest {
    return true;
}

export function CreateUserSubscriptionFilterRequestFromJSON(json: any): CreateUserSubscriptionFilterRequest {
    return CreateUserSubscriptionFilterRequestFromJSONTyped(json, false);
}

export function CreateUserSubscriptionFilterRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateUserSubscriptionFilterRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'sourceType': json['source_type'] == null ? undefined : json['source_type'],
        'b': json['b'] == null ? undefined : json['b'],
        'r': json['r'] == null ? undefined : json['r'],
        'filterParameters': json['filterParameters'] == null ? undefined : json['filterParameters'],
    };
}

export function CreateUserSubscriptionFilterRequestToJSON(json: any): CreateUserSubscriptionFilterRequest {
    return CreateUserSubscriptionFilterRequestToJSONTyped(json, false);
}

export function CreateUserSubscriptionFilterRequestToJSONTyped(value?: CreateUserSubscriptionFilterRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'source_type': value['sourceType'],
        'b': value['b'],
        'r': value['r'],
        'filterParameters': value['filterParameters'],
    };
}

