/* tslint:disable */
/* eslint-disable */
/**
 * My App
 * This is an awesome app!
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetAppSpecautocontextPresentationBrandgetcollectionGetbrands200ResponseInner
 */
export interface GetAppSpecautocontextPresentationBrandgetcollectionGetbrands200ResponseInner {
    /**
     * 
     * @type {number}
     * @memberof GetAppSpecautocontextPresentationBrandgetcollectionGetbrands200ResponseInner
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof GetAppSpecautocontextPresentationBrandgetcollectionGetbrands200ResponseInner
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof GetAppSpecautocontextPresentationBrandgetcollectionGetbrands200ResponseInner
     */
    orderNumber?: number;
}

/**
 * Check if a given object implements the GetAppSpecautocontextPresentationBrandgetcollectionGetbrands200ResponseInner interface.
 */
export function instanceOfGetAppSpecautocontextPresentationBrandgetcollectionGetbrands200ResponseInner(value: object): value is GetAppSpecautocontextPresentationBrandgetcollectionGetbrands200ResponseInner {
    return true;
}

export function GetAppSpecautocontextPresentationBrandgetcollectionGetbrands200ResponseInnerFromJSON(json: any): GetAppSpecautocontextPresentationBrandgetcollectionGetbrands200ResponseInner {
    return GetAppSpecautocontextPresentationBrandgetcollectionGetbrands200ResponseInnerFromJSONTyped(json, false);
}

export function GetAppSpecautocontextPresentationBrandgetcollectionGetbrands200ResponseInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAppSpecautocontextPresentationBrandgetcollectionGetbrands200ResponseInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'orderNumber': json['orderNumber'] == null ? undefined : json['orderNumber'],
    };
}

export function GetAppSpecautocontextPresentationBrandgetcollectionGetbrands200ResponseInnerToJSON(json: any): GetAppSpecautocontextPresentationBrandgetcollectionGetbrands200ResponseInner {
    return GetAppSpecautocontextPresentationBrandgetcollectionGetbrands200ResponseInnerToJSONTyped(json, false);
}

export function GetAppSpecautocontextPresentationBrandgetcollectionGetbrands200ResponseInnerToJSONTyped(value?: GetAppSpecautocontextPresentationBrandgetcollectionGetbrands200ResponseInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'orderNumber': value['orderNumber'],
    };
}

