/* tslint:disable */
/* eslint-disable */
/**
 * My App
 * This is an awesome app!
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetAppUserdomainPresentationGetmeGetme200ResponseRecentProductsInner
 */
export interface GetAppUserdomainPresentationGetmeGetme200ResponseRecentProductsInner {
    /**
     * 
     * @type {string}
     * @memberof GetAppUserdomainPresentationGetmeGetme200ResponseRecentProductsInner
     */
    slug?: string;
    /**
     * 
     * @type {string}
     * @memberof GetAppUserdomainPresentationGetmeGetme200ResponseRecentProductsInner
     */
    name?: string;
}

/**
 * Check if a given object implements the GetAppUserdomainPresentationGetmeGetme200ResponseRecentProductsInner interface.
 */
export function instanceOfGetAppUserdomainPresentationGetmeGetme200ResponseRecentProductsInner(value: object): value is GetAppUserdomainPresentationGetmeGetme200ResponseRecentProductsInner {
    return true;
}

export function GetAppUserdomainPresentationGetmeGetme200ResponseRecentProductsInnerFromJSON(json: any): GetAppUserdomainPresentationGetmeGetme200ResponseRecentProductsInner {
    return GetAppUserdomainPresentationGetmeGetme200ResponseRecentProductsInnerFromJSONTyped(json, false);
}

export function GetAppUserdomainPresentationGetmeGetme200ResponseRecentProductsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAppUserdomainPresentationGetmeGetme200ResponseRecentProductsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'slug': json['slug'] == null ? undefined : json['slug'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function GetAppUserdomainPresentationGetmeGetme200ResponseRecentProductsInnerToJSON(json: any): GetAppUserdomainPresentationGetmeGetme200ResponseRecentProductsInner {
    return GetAppUserdomainPresentationGetmeGetme200ResponseRecentProductsInnerToJSONTyped(json, false);
}

export function GetAppUserdomainPresentationGetmeGetme200ResponseRecentProductsInnerToJSONTyped(value?: GetAppUserdomainPresentationGetmeGetme200ResponseRecentProductsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'slug': value['slug'],
        'name': value['name'],
    };
}

