/* tslint:disable */
/* eslint-disable */
/**
 * My App
 * This is an awesome app!
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetAppUserdomainPresentationGetmeGetme200ResponseRecentProductsInner } from './GetAppUserdomainPresentationGetmeGetme200ResponseRecentProductsInner';
import {
    GetAppUserdomainPresentationGetmeGetme200ResponseRecentProductsInnerFromJSON,
    GetAppUserdomainPresentationGetmeGetme200ResponseRecentProductsInnerFromJSONTyped,
    GetAppUserdomainPresentationGetmeGetme200ResponseRecentProductsInnerToJSON,
    GetAppUserdomainPresentationGetmeGetme200ResponseRecentProductsInnerToJSONTyped,
} from './GetAppUserdomainPresentationGetmeGetme200ResponseRecentProductsInner';

/**
 * 
 * @export
 * @interface GetAppUserdomainPresentationGetmeGetme200Response
 */
export interface GetAppUserdomainPresentationGetmeGetme200Response {
    /**
     * 
     * @type {string}
     * @memberof GetAppUserdomainPresentationGetmeGetme200Response
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof GetAppUserdomainPresentationGetmeGetme200Response
     */
    email?: string;
    /**
     * 
     * @type {Array<GetAppUserdomainPresentationGetmeGetme200ResponseRecentProductsInner>}
     * @memberof GetAppUserdomainPresentationGetmeGetme200Response
     */
    recentProducts?: Array<GetAppUserdomainPresentationGetmeGetme200ResponseRecentProductsInner>;
}

/**
 * Check if a given object implements the GetAppUserdomainPresentationGetmeGetme200Response interface.
 */
export function instanceOfGetAppUserdomainPresentationGetmeGetme200Response(value: object): value is GetAppUserdomainPresentationGetmeGetme200Response {
    return true;
}

export function GetAppUserdomainPresentationGetmeGetme200ResponseFromJSON(json: any): GetAppUserdomainPresentationGetmeGetme200Response {
    return GetAppUserdomainPresentationGetmeGetme200ResponseFromJSONTyped(json, false);
}

export function GetAppUserdomainPresentationGetmeGetme200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAppUserdomainPresentationGetmeGetme200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'email': json['email'] == null ? undefined : json['email'],
        'recentProducts': json['recentProducts'] == null ? undefined : ((json['recentProducts'] as Array<any>).map(GetAppUserdomainPresentationGetmeGetme200ResponseRecentProductsInnerFromJSON)),
    };
}

export function GetAppUserdomainPresentationGetmeGetme200ResponseToJSON(json: any): GetAppUserdomainPresentationGetmeGetme200Response {
    return GetAppUserdomainPresentationGetmeGetme200ResponseToJSONTyped(json, false);
}

export function GetAppUserdomainPresentationGetmeGetme200ResponseToJSONTyped(value?: GetAppUserdomainPresentationGetmeGetme200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'email': value['email'],
        'recentProducts': value['recentProducts'] == null ? undefined : ((value['recentProducts'] as Array<any>).map(GetAppUserdomainPresentationGetmeGetme200ResponseRecentProductsInnerToJSON)),
    };
}

