/* tslint:disable */
/* eslint-disable */
/**
 * My App
 * This is an awesome app!
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetAppSimpleautocontextPresentationSimpleautogetcollectionGetcollectionbyfilters200ResponseInner
 */
export interface GetAppSimpleautocontextPresentationSimpleautogetcollectionGetcollectionbyfilters200ResponseInner {
    /**
     * 
     * @type {string}
     * @memberof GetAppSimpleautocontextPresentationSimpleautogetcollectionGetcollectionbyfilters200ResponseInner
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof GetAppSimpleautocontextPresentationSimpleautogetcollectionGetcollectionbyfilters200ResponseInner
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof GetAppSimpleautocontextPresentationSimpleautogetcollectionGetcollectionbyfilters200ResponseInner
     */
    brand?: string;
    /**
     * 
     * @type {string}
     * @memberof GetAppSimpleautocontextPresentationSimpleautogetcollectionGetcollectionbyfilters200ResponseInner
     */
    model?: string;
    /**
     * 
     * @type {string}
     * @memberof GetAppSimpleautocontextPresentationSimpleautogetcollectionGetcollectionbyfilters200ResponseInner
     */
    priceFrom?: string;
    /**
     * 
     * @type {string}
     * @memberof GetAppSimpleautocontextPresentationSimpleautogetcollectionGetcollectionbyfilters200ResponseInner
     */
    priceTo?: string;
    /**
     * 
     * @type {string}
     * @memberof GetAppSimpleautocontextPresentationSimpleautogetcollectionGetcollectionbyfilters200ResponseInner
     */
    currency?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof GetAppSimpleautocontextPresentationSimpleautogetcollectionGetcollectionbyfilters200ResponseInner
     */
    regions?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof GetAppSimpleautocontextPresentationSimpleautogetcollectionGetcollectionbyfilters200ResponseInner
     */
    releaseYearFrom?: number;
    /**
     * 
     * @type {number}
     * @memberof GetAppSimpleautocontextPresentationSimpleautogetcollectionGetcollectionbyfilters200ResponseInner
     */
    releaseYearTo?: number;
    /**
     * 
     * @type {Array<object>}
     * @memberof GetAppSimpleautocontextPresentationSimpleautogetcollectionGetcollectionbyfilters200ResponseInner
     */
    parameters?: Array<object>;
}

/**
 * Check if a given object implements the GetAppSimpleautocontextPresentationSimpleautogetcollectionGetcollectionbyfilters200ResponseInner interface.
 */
export function instanceOfGetAppSimpleautocontextPresentationSimpleautogetcollectionGetcollectionbyfilters200ResponseInner(value: object): value is GetAppSimpleautocontextPresentationSimpleautogetcollectionGetcollectionbyfilters200ResponseInner {
    return true;
}

export function GetAppSimpleautocontextPresentationSimpleautogetcollectionGetcollectionbyfilters200ResponseInnerFromJSON(json: any): GetAppSimpleautocontextPresentationSimpleautogetcollectionGetcollectionbyfilters200ResponseInner {
    return GetAppSimpleautocontextPresentationSimpleautogetcollectionGetcollectionbyfilters200ResponseInnerFromJSONTyped(json, false);
}

export function GetAppSimpleautocontextPresentationSimpleautogetcollectionGetcollectionbyfilters200ResponseInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAppSimpleautocontextPresentationSimpleautogetcollectionGetcollectionbyfilters200ResponseInner {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'brand': json['brand'] == null ? undefined : json['brand'],
        'model': json['model'] == null ? undefined : json['model'],
        'priceFrom': json['priceFrom'] == null ? undefined : json['priceFrom'],
        'priceTo': json['priceTo'] == null ? undefined : json['priceTo'],
        'currency': json['currency'] == null ? undefined : json['currency'],
        'regions': json['regions'] == null ? undefined : json['regions'],
        'releaseYearFrom': json['releaseYearFrom'] == null ? undefined : json['releaseYearFrom'],
        'releaseYearTo': json['releaseYearTo'] == null ? undefined : json['releaseYearTo'],
        'parameters': json['parameters'] == null ? undefined : json['parameters'],
    };
}

export function GetAppSimpleautocontextPresentationSimpleautogetcollectionGetcollectionbyfilters200ResponseInnerToJSON(json: any): GetAppSimpleautocontextPresentationSimpleautogetcollectionGetcollectionbyfilters200ResponseInner {
    return GetAppSimpleautocontextPresentationSimpleautogetcollectionGetcollectionbyfilters200ResponseInnerToJSONTyped(json, false);
}

export function GetAppSimpleautocontextPresentationSimpleautogetcollectionGetcollectionbyfilters200ResponseInnerToJSONTyped(value?: GetAppSimpleautocontextPresentationSimpleautogetcollectionGetcollectionbyfilters200ResponseInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'brand': value['brand'],
        'model': value['model'],
        'priceFrom': value['priceFrom'],
        'priceTo': value['priceTo'],
        'currency': value['currency'],
        'regions': value['regions'],
        'releaseYearFrom': value['releaseYearFrom'],
        'releaseYearTo': value['releaseYearTo'],
        'parameters': value['parameters'],
    };
}

