/* tslint:disable */
/* eslint-disable */
/**
 * My App
 * This is an awesome app!
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetAppSimpleautocontextPresentationSimpleautogetoneGetcollectionbyfilters200Response
 */
export interface GetAppSimpleautocontextPresentationSimpleautogetoneGetcollectionbyfilters200Response {
    /**
     * 
     * @type {string}
     * @memberof GetAppSimpleautocontextPresentationSimpleautogetoneGetcollectionbyfilters200Response
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof GetAppSimpleautocontextPresentationSimpleautogetoneGetcollectionbyfilters200Response
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof GetAppSimpleautocontextPresentationSimpleautogetoneGetcollectionbyfilters200Response
     */
    brand?: string;
    /**
     * 
     * @type {string}
     * @memberof GetAppSimpleautocontextPresentationSimpleautogetoneGetcollectionbyfilters200Response
     */
    model?: string;
    /**
     * 
     * @type {string}
     * @memberof GetAppSimpleautocontextPresentationSimpleautogetoneGetcollectionbyfilters200Response
     */
    price?: string;
    /**
     * 
     * @type {string}
     * @memberof GetAppSimpleautocontextPresentationSimpleautogetoneGetcollectionbyfilters200Response
     */
    currency?: string;
    /**
     * 
     * @type {string}
     * @memberof GetAppSimpleautocontextPresentationSimpleautogetoneGetcollectionbyfilters200Response
     */
    region?: string;
    /**
     * 
     * @type {number}
     * @memberof GetAppSimpleautocontextPresentationSimpleautogetoneGetcollectionbyfilters200Response
     */
    releaseYear?: number;
    /**
     * 
     * @type {Array<object>}
     * @memberof GetAppSimpleautocontextPresentationSimpleautogetoneGetcollectionbyfilters200Response
     */
    parameters?: Array<object>;
}

/**
 * Check if a given object implements the GetAppSimpleautocontextPresentationSimpleautogetoneGetcollectionbyfilters200Response interface.
 */
export function instanceOfGetAppSimpleautocontextPresentationSimpleautogetoneGetcollectionbyfilters200Response(value: object): value is GetAppSimpleautocontextPresentationSimpleautogetoneGetcollectionbyfilters200Response {
    return true;
}

export function GetAppSimpleautocontextPresentationSimpleautogetoneGetcollectionbyfilters200ResponseFromJSON(json: any): GetAppSimpleautocontextPresentationSimpleautogetoneGetcollectionbyfilters200Response {
    return GetAppSimpleautocontextPresentationSimpleautogetoneGetcollectionbyfilters200ResponseFromJSONTyped(json, false);
}

export function GetAppSimpleautocontextPresentationSimpleautogetoneGetcollectionbyfilters200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAppSimpleautocontextPresentationSimpleautogetoneGetcollectionbyfilters200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'brand': json['brand'] == null ? undefined : json['brand'],
        'model': json['model'] == null ? undefined : json['model'],
        'price': json['price'] == null ? undefined : json['price'],
        'currency': json['currency'] == null ? undefined : json['currency'],
        'region': json['region'] == null ? undefined : json['region'],
        'releaseYear': json['releaseYear'] == null ? undefined : json['releaseYear'],
        'parameters': json['parameters'] == null ? undefined : json['parameters'],
    };
}

export function GetAppSimpleautocontextPresentationSimpleautogetoneGetcollectionbyfilters200ResponseToJSON(json: any): GetAppSimpleautocontextPresentationSimpleautogetoneGetcollectionbyfilters200Response {
    return GetAppSimpleautocontextPresentationSimpleautogetoneGetcollectionbyfilters200ResponseToJSONTyped(json, false);
}

export function GetAppSimpleautocontextPresentationSimpleautogetoneGetcollectionbyfilters200ResponseToJSONTyped(value?: GetAppSimpleautocontextPresentationSimpleautogetoneGetcollectionbyfilters200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'brand': value['brand'],
        'model': value['model'],
        'price': value['price'],
        'currency': value['currency'],
        'region': value['region'],
        'releaseYear': value['releaseYear'],
        'parameters': value['parameters'],
    };
}

