/* tslint:disable */
/* eslint-disable */
/**
 * My App
 * This is an awesome app!
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetAppSpecautocontextPresentationModelgetcollectionGetcollectionbyfilters200ResponseInner
 */
export interface GetAppSpecautocontextPresentationModelgetcollectionGetcollectionbyfilters200ResponseInner {
    /**
     * 
     * @type {string}
     * @memberof GetAppSpecautocontextPresentationModelgetcollectionGetcollectionbyfilters200ResponseInner
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof GetAppSpecautocontextPresentationModelgetcollectionGetcollectionbyfilters200ResponseInner
     */
    orderNumber?: number;
}

/**
 * Check if a given object implements the GetAppSpecautocontextPresentationModelgetcollectionGetcollectionbyfilters200ResponseInner interface.
 */
export function instanceOfGetAppSpecautocontextPresentationModelgetcollectionGetcollectionbyfilters200ResponseInner(value: object): value is GetAppSpecautocontextPresentationModelgetcollectionGetcollectionbyfilters200ResponseInner {
    return true;
}

export function GetAppSpecautocontextPresentationModelgetcollectionGetcollectionbyfilters200ResponseInnerFromJSON(json: any): GetAppSpecautocontextPresentationModelgetcollectionGetcollectionbyfilters200ResponseInner {
    return GetAppSpecautocontextPresentationModelgetcollectionGetcollectionbyfilters200ResponseInnerFromJSONTyped(json, false);
}

export function GetAppSpecautocontextPresentationModelgetcollectionGetcollectionbyfilters200ResponseInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAppSpecautocontextPresentationModelgetcollectionGetcollectionbyfilters200ResponseInner {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'orderNumber': json['orderNumber'] == null ? undefined : json['orderNumber'],
    };
}

export function GetAppSpecautocontextPresentationModelgetcollectionGetcollectionbyfilters200ResponseInnerToJSON(json: any): GetAppSpecautocontextPresentationModelgetcollectionGetcollectionbyfilters200ResponseInner {
    return GetAppSpecautocontextPresentationModelgetcollectionGetcollectionbyfilters200ResponseInnerToJSONTyped(json, false);
}

export function GetAppSpecautocontextPresentationModelgetcollectionGetcollectionbyfilters200ResponseInnerToJSONTyped(value?: GetAppSpecautocontextPresentationModelgetcollectionGetcollectionbyfilters200ResponseInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'orderNumber': value['orderNumber'],
    };
}

