/* tslint:disable */
/* eslint-disable */
/**
 * My App
 * This is an awesome app!
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetChats200ResponseInnerMessagesInner
 */
export interface GetChats200ResponseInnerMessagesInner {
    /**
     * 
     * @type {number}
     * @memberof GetChats200ResponseInnerMessagesInner
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof GetChats200ResponseInnerMessagesInner
     */
    sender?: number;
    /**
     * 
     * @type {string}
     * @memberof GetChats200ResponseInnerMessagesInner
     */
    content?: string;
    /**
     * 
     * @type {Date}
     * @memberof GetChats200ResponseInnerMessagesInner
     */
    createdAt?: Date;
}

/**
 * Check if a given object implements the GetChats200ResponseInnerMessagesInner interface.
 */
export function instanceOfGetChats200ResponseInnerMessagesInner(value: object): value is GetChats200ResponseInnerMessagesInner {
    return true;
}

export function GetChats200ResponseInnerMessagesInnerFromJSON(json: any): GetChats200ResponseInnerMessagesInner {
    return GetChats200ResponseInnerMessagesInnerFromJSONTyped(json, false);
}

export function GetChats200ResponseInnerMessagesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetChats200ResponseInnerMessagesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'sender': json['sender'] == null ? undefined : json['sender'],
        'content': json['content'] == null ? undefined : json['content'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
    };
}

export function GetChats200ResponseInnerMessagesInnerToJSON(json: any): GetChats200ResponseInnerMessagesInner {
    return GetChats200ResponseInnerMessagesInnerToJSONTyped(json, false);
}

export function GetChats200ResponseInnerMessagesInnerToJSONTyped(value?: GetChats200ResponseInnerMessagesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'sender': value['sender'],
        'content': value['content'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
    };
}

