/* tslint:disable */
/* eslint-disable */
/**
 * My App
 * This is an awesome app!
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetChatSubscriptionInfo200Response
 */
export interface GetChatSubscriptionInfo200Response {
    /**
     * 
     * @type {string}
     * @memberof GetChatSubscriptionInfo200Response
     */
    topic?: string;
    /**
     * 
     * @type {string}
     * @memberof GetChatSubscriptionInfo200Response
     */
    mercureUrl?: string;
}

/**
 * Check if a given object implements the GetChatSubscriptionInfo200Response interface.
 */
export function instanceOfGetChatSubscriptionInfo200Response(value: object): value is GetChatSubscriptionInfo200Response {
    return true;
}

export function GetChatSubscriptionInfo200ResponseFromJSON(json: any): GetChatSubscriptionInfo200Response {
    return GetChatSubscriptionInfo200ResponseFromJSONTyped(json, false);
}

export function GetChatSubscriptionInfo200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetChatSubscriptionInfo200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'topic': json['topic'] == null ? undefined : json['topic'],
        'mercureUrl': json['mercureUrl'] == null ? undefined : json['mercureUrl'],
    };
}

export function GetChatSubscriptionInfo200ResponseToJSON(json: any): GetChatSubscriptionInfo200Response {
    return GetChatSubscriptionInfo200ResponseToJSONTyped(json, false);
}

export function GetChatSubscriptionInfo200ResponseToJSONTyped(value?: GetChatSubscriptionInfo200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'topic': value['topic'],
        'mercureUrl': value['mercureUrl'],
    };
}

