/* tslint:disable */
/* eslint-disable */
/**
 * My App
 * This is an awesome app!
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdvertisementItemResponse } from './AdvertisementItemResponse';
import {
    AdvertisementItemResponseFromJSON,
    AdvertisementItemResponseFromJSONTyped,
    AdvertisementItemResponseToJSON,
    AdvertisementItemResponseToJSONTyped,
} from './AdvertisementItemResponse';

/**
 * 
 * @export
 * @interface GetSimpleAutoCollectionPagination200Response
 */
export interface GetSimpleAutoCollectionPagination200Response {
    /**
     * 
     * @type {number}
     * @memberof GetSimpleAutoCollectionPagination200Response
     */
    total: number;
    /**
     * 
     * @type {number}
     * @memberof GetSimpleAutoCollectionPagination200Response
     */
    currentPage: number;
    /**
     * 
     * @type {number}
     * @memberof GetSimpleAutoCollectionPagination200Response
     */
    perPage: number;
    /**
     * 
     * @type {Array<AdvertisementItemResponse>}
     * @memberof GetSimpleAutoCollectionPagination200Response
     */
    items: Array<AdvertisementItemResponse>;
}

/**
 * Check if a given object implements the GetSimpleAutoCollectionPagination200Response interface.
 */
export function instanceOfGetSimpleAutoCollectionPagination200Response(value: object): value is GetSimpleAutoCollectionPagination200Response {
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('currentPage' in value) || value['currentPage'] === undefined) return false;
    if (!('perPage' in value) || value['perPage'] === undefined) return false;
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function GetSimpleAutoCollectionPagination200ResponseFromJSON(json: any): GetSimpleAutoCollectionPagination200Response {
    return GetSimpleAutoCollectionPagination200ResponseFromJSONTyped(json, false);
}

export function GetSimpleAutoCollectionPagination200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetSimpleAutoCollectionPagination200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'total': json['total'],
        'currentPage': json['currentPage'],
        'perPage': json['perPage'],
        'items': ((json['items'] as Array<any>).map(AdvertisementItemResponseFromJSON)),
    };
}

export function GetSimpleAutoCollectionPagination200ResponseToJSON(json: any): GetSimpleAutoCollectionPagination200Response {
    return GetSimpleAutoCollectionPagination200ResponseToJSONTyped(json, false);
}

export function GetSimpleAutoCollectionPagination200ResponseToJSONTyped(value?: GetSimpleAutoCollectionPagination200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total': value['total'],
        'currentPage': value['currentPage'],
        'perPage': value['perPage'],
        'items': ((value['items'] as Array<any>).map(AdvertisementItemResponseToJSON)),
    };
}

