/* tslint:disable */
/* eslint-disable */
/**
 * My App
 * This is an awesome app!
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserAdvertisementItemResponse } from './UserAdvertisementItemResponse';
import {
    UserAdvertisementItemResponseFromJSON,
    UserAdvertisementItemResponseFromJSONTyped,
    UserAdvertisementItemResponseToJSON,
    UserAdvertisementItemResponseToJSONTyped,
} from './UserAdvertisementItemResponse';

/**
 * 
 * @export
 * @interface GetUserAdvertisements200Response
 */
export interface GetUserAdvertisements200Response {
    /**
     * 
     * @type {number}
     * @memberof GetUserAdvertisements200Response
     */
    total?: number;
    /**
     * 
     * @type {number}
     * @memberof GetUserAdvertisements200Response
     */
    currentPage?: number;
    /**
     * 
     * @type {number}
     * @memberof GetUserAdvertisements200Response
     */
    perPage?: number;
    /**
     * 
     * @type {Array<UserAdvertisementItemResponse>}
     * @memberof GetUserAdvertisements200Response
     */
    items?: Array<UserAdvertisementItemResponse>;
}

/**
 * Check if a given object implements the GetUserAdvertisements200Response interface.
 */
export function instanceOfGetUserAdvertisements200Response(value: object): value is GetUserAdvertisements200Response {
    return true;
}

export function GetUserAdvertisements200ResponseFromJSON(json: any): GetUserAdvertisements200Response {
    return GetUserAdvertisements200ResponseFromJSONTyped(json, false);
}

export function GetUserAdvertisements200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetUserAdvertisements200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'total': json['total'] == null ? undefined : json['total'],
        'currentPage': json['currentPage'] == null ? undefined : json['currentPage'],
        'perPage': json['perPage'] == null ? undefined : json['perPage'],
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(UserAdvertisementItemResponseFromJSON)),
    };
}

export function GetUserAdvertisements200ResponseToJSON(json: any): GetUserAdvertisements200Response {
    return GetUserAdvertisements200ResponseToJSONTyped(json, false);
}

export function GetUserAdvertisements200ResponseToJSONTyped(value?: GetUserAdvertisements200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total': value['total'],
        'currentPage': value['currentPage'],
        'perPage': value['perPage'],
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(UserAdvertisementItemResponseToJSON)),
    };
}

