/* tslint:disable */
/* eslint-disable */
/**
 * My App
 * This is an awesome app!
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetUserFavorites200ResponseItemsInner
 */
export interface GetUserFavorites200ResponseItemsInner {
    /**
     * 
     * @type {number}
     * @memberof GetUserFavorites200ResponseItemsInner
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof GetUserFavorites200ResponseItemsInner
     */
    advertisementId?: number;
    /**
     * 
     * @type {string}
     * @memberof GetUserFavorites200ResponseItemsInner
     */
    brand?: string;
    /**
     * 
     * @type {string}
     * @memberof GetUserFavorites200ResponseItemsInner
     */
    model?: string;
    /**
     * 
     * @type {string}
     * @memberof GetUserFavorites200ResponseItemsInner
     */
    price?: string;
    /**
     * 
     * @type {string}
     * @memberof GetUserFavorites200ResponseItemsInner
     */
    currency?: string;
    /**
     * 
     * @type {number}
     * @memberof GetUserFavorites200ResponseItemsInner
     */
    releaseYear?: number;
    /**
     * 
     * @type {string}
     * @memberof GetUserFavorites200ResponseItemsInner
     */
    region?: string;
    /**
     * 
     * @type {Date}
     * @memberof GetUserFavorites200ResponseItemsInner
     */
    createdAt?: Date;
    /**
     * 
     * @type {Array<string>}
     * @memberof GetUserFavorites200ResponseItemsInner
     */
    images?: Array<string>;
}

/**
 * Check if a given object implements the GetUserFavorites200ResponseItemsInner interface.
 */
export function instanceOfGetUserFavorites200ResponseItemsInner(value: object): value is GetUserFavorites200ResponseItemsInner {
    return true;
}

export function GetUserFavorites200ResponseItemsInnerFromJSON(json: any): GetUserFavorites200ResponseItemsInner {
    return GetUserFavorites200ResponseItemsInnerFromJSONTyped(json, false);
}

export function GetUserFavorites200ResponseItemsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetUserFavorites200ResponseItemsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'advertisementId': json['advertisementId'] == null ? undefined : json['advertisementId'],
        'brand': json['brand'] == null ? undefined : json['brand'],
        'model': json['model'] == null ? undefined : json['model'],
        'price': json['price'] == null ? undefined : json['price'],
        'currency': json['currency'] == null ? undefined : json['currency'],
        'releaseYear': json['releaseYear'] == null ? undefined : json['releaseYear'],
        'region': json['region'] == null ? undefined : json['region'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'images': json['images'] == null ? undefined : json['images'],
    };
}

export function GetUserFavorites200ResponseItemsInnerToJSON(json: any): GetUserFavorites200ResponseItemsInner {
    return GetUserFavorites200ResponseItemsInnerToJSONTyped(json, false);
}

export function GetUserFavorites200ResponseItemsInnerToJSONTyped(value?: GetUserFavorites200ResponseItemsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'advertisementId': value['advertisementId'],
        'brand': value['brand'],
        'model': value['model'],
        'price': value['price'],
        'currency': value['currency'],
        'releaseYear': value['releaseYear'],
        'region': value['region'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'images': value['images'],
    };
}

