/* tslint:disable */
/* eslint-disable */
/**
 * My App
 * This is an awesome app!
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetUserAdvertisements200ResponseItemsInner
 */
export interface GetUserAdvertisements200ResponseItemsInner {
    /**
     * 
     * @type {number}
     * @memberof GetUserAdvertisements200ResponseItemsInner
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof GetUserAdvertisements200ResponseItemsInner
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof GetUserAdvertisements200ResponseItemsInner
     */
    brand?: string;
    /**
     * 
     * @type {string}
     * @memberof GetUserAdvertisements200ResponseItemsInner
     */
    model?: string;
    /**
     * 
     * @type {string}
     * @memberof GetUserAdvertisements200ResponseItemsInner
     */
    price?: string;
    /**
     * 
     * @type {string}
     * @memberof GetUserAdvertisements200ResponseItemsInner
     */
    currency?: string;
    /**
     * 
     * @type {number}
     * @memberof GetUserAdvertisements200ResponseItemsInner
     */
    releaseYear?: number;
    /**
     * 
     * @type {string}
     * @memberof GetUserAdvertisements200ResponseItemsInner
     */
    region?: string;
    /**
     * 
     * @type {boolean}
     * @memberof GetUserAdvertisements200ResponseItemsInner
     */
    isVerified?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof GetUserAdvertisements200ResponseItemsInner
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof GetUserAdvertisements200ResponseItemsInner
     */
    updatedAt?: Date;
    /**
     * 
     * @type {Array<string>}
     * @memberof GetUserAdvertisements200ResponseItemsInner
     */
    images?: Array<string>;
}

/**
 * Check if a given object implements the GetUserAdvertisements200ResponseItemsInner interface.
 */
export function instanceOfGetUserAdvertisements200ResponseItemsInner(value: object): value is GetUserAdvertisements200ResponseItemsInner {
    return true;
}

export function GetUserAdvertisements200ResponseItemsInnerFromJSON(json: any): GetUserAdvertisements200ResponseItemsInner {
    return GetUserAdvertisements200ResponseItemsInnerFromJSONTyped(json, false);
}

export function GetUserAdvertisements200ResponseItemsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetUserAdvertisements200ResponseItemsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'description': json['description'] == null ? undefined : json['description'],
        'brand': json['brand'] == null ? undefined : json['brand'],
        'model': json['model'] == null ? undefined : json['model'],
        'price': json['price'] == null ? undefined : json['price'],
        'currency': json['currency'] == null ? undefined : json['currency'],
        'releaseYear': json['releaseYear'] == null ? undefined : json['releaseYear'],
        'region': json['region'] == null ? undefined : json['region'],
        'isVerified': json['isVerified'] == null ? undefined : json['isVerified'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'images': json['images'] == null ? undefined : json['images'],
    };
}

export function GetUserAdvertisements200ResponseItemsInnerToJSON(json: any): GetUserAdvertisements200ResponseItemsInner {
    return GetUserAdvertisements200ResponseItemsInnerToJSONTyped(json, false);
}

export function GetUserAdvertisements200ResponseItemsInnerToJSONTyped(value?: GetUserAdvertisements200ResponseItemsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'description': value['description'],
        'brand': value['brand'],
        'model': value['model'],
        'price': value['price'],
        'currency': value['currency'],
        'releaseYear': value['releaseYear'],
        'region': value['region'],
        'isVerified': value['isVerified'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
        'images': value['images'],
    };
}

