/* tslint:disable */
/* eslint-disable */
/**
 * My App
 * This is an awesome app!
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetUserFavorites200ResponseItemsInner } from './GetUserFavorites200ResponseItemsInner';
import {
    GetUserFavorites200ResponseItemsInnerFromJSON,
    GetUserFavorites200ResponseItemsInnerFromJSONTyped,
    GetUserFavorites200ResponseItemsInnerToJSON,
    GetUserFavorites200ResponseItemsInnerToJSONTyped,
} from './GetUserFavorites200ResponseItemsInner';

/**
 * 
 * @export
 * @interface GetUserFavorites200Response
 */
export interface GetUserFavorites200Response {
    /**
     * 
     * @type {number}
     * @memberof GetUserFavorites200Response
     */
    total?: number;
    /**
     * 
     * @type {number}
     * @memberof GetUserFavorites200Response
     */
    currentPage?: number;
    /**
     * 
     * @type {number}
     * @memberof GetUserFavorites200Response
     */
    perPage?: number;
    /**
     * 
     * @type {Array<GetUserFavorites200ResponseItemsInner>}
     * @memberof GetUserFavorites200Response
     */
    items?: Array<GetUserFavorites200ResponseItemsInner>;
}

/**
 * Check if a given object implements the GetUserFavorites200Response interface.
 */
export function instanceOfGetUserFavorites200Response(value: object): value is GetUserFavorites200Response {
    return true;
}

export function GetUserFavorites200ResponseFromJSON(json: any): GetUserFavorites200Response {
    return GetUserFavorites200ResponseFromJSONTyped(json, false);
}

export function GetUserFavorites200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetUserFavorites200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'total': json['total'] == null ? undefined : json['total'],
        'currentPage': json['currentPage'] == null ? undefined : json['currentPage'],
        'perPage': json['perPage'] == null ? undefined : json['perPage'],
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(GetUserFavorites200ResponseItemsInnerFromJSON)),
    };
}

export function GetUserFavorites200ResponseToJSON(json: any): GetUserFavorites200Response {
    return GetUserFavorites200ResponseToJSONTyped(json, false);
}

export function GetUserFavorites200ResponseToJSONTyped(value?: GetUserFavorites200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total': value['total'],
        'currentPage': value['currentPage'],
        'perPage': value['perPage'],
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(GetUserFavorites200ResponseItemsInnerToJSON)),
    };
}

