/* tslint:disable */
/* eslint-disable */
/**
 * My App
 * This is an awesome app!
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetUserNotifications200ResponseInner
 */
export interface GetUserNotifications200ResponseInner {
    /**
     * 
     * @type {number}
     * @memberof GetUserNotifications200ResponseInner
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof GetUserNotifications200ResponseInner
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof GetUserNotifications200ResponseInner
     */
    body?: string;
    /**
     * 
     * @type {string}
     * @memberof GetUserNotifications200ResponseInner
     */
    status?: string;
    /**
     * 
     * @type {Date}
     * @memberof GetUserNotifications200ResponseInner
     */
    sentAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof GetUserNotifications200ResponseInner
     */
    createdAt?: Date;
}

/**
 * Check if a given object implements the GetUserNotifications200ResponseInner interface.
 */
export function instanceOfGetUserNotifications200ResponseInner(value: object): value is GetUserNotifications200ResponseInner {
    return true;
}

export function GetUserNotifications200ResponseInnerFromJSON(json: any): GetUserNotifications200ResponseInner {
    return GetUserNotifications200ResponseInnerFromJSONTyped(json, false);
}

export function GetUserNotifications200ResponseInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetUserNotifications200ResponseInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'] == null ? undefined : json['title'],
        'body': json['body'] == null ? undefined : json['body'],
        'status': json['status'] == null ? undefined : json['status'],
        'sentAt': json['sentAt'] == null ? undefined : (new Date(json['sentAt'])),
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
    };
}

export function GetUserNotifications200ResponseInnerToJSON(json: any): GetUserNotifications200ResponseInner {
    return GetUserNotifications200ResponseInnerToJSONTyped(json, false);
}

export function GetUserNotifications200ResponseInnerToJSONTyped(value?: GetUserNotifications200ResponseInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'body': value['body'],
        'status': value['status'],
        'sentAt': value['sentAt'] == null ? value['sentAt'] : value['sentAt'].toISOString(),
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
    };
}

