/* tslint:disable */
/* eslint-disable */
/**
 * My App
 * This is an awesome app!
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetUserSubscriptionFilter200Response
 */
export interface GetUserSubscriptionFilter200Response {
    /**
     * 
     * @type {number}
     * @memberof GetUserSubscriptionFilter200Response
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof GetUserSubscriptionFilter200Response
     */
    name?: string;
    /**
     * 
     * @type {Array<object>}
     * @memberof GetUserSubscriptionFilter200Response
     */
    filters?: Array<object>;
}

/**
 * Check if a given object implements the GetUserSubscriptionFilter200Response interface.
 */
export function instanceOfGetUserSubscriptionFilter200Response(value: object): value is GetUserSubscriptionFilter200Response {
    return true;
}

export function GetUserSubscriptionFilter200ResponseFromJSON(json: any): GetUserSubscriptionFilter200Response {
    return GetUserSubscriptionFilter200ResponseFromJSONTyped(json, false);
}

export function GetUserSubscriptionFilter200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetUserSubscriptionFilter200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'filters': json['filters'] == null ? undefined : json['filters'],
    };
}

export function GetUserSubscriptionFilter200ResponseToJSON(json: any): GetUserSubscriptionFilter200Response {
    return GetUserSubscriptionFilter200ResponseToJSONTyped(json, false);
}

export function GetUserSubscriptionFilter200ResponseToJSONTyped(value?: GetUserSubscriptionFilter200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'filters': value['filters'],
    };
}

