/* tslint:disable */
/* eslint-disable */
/**
 * My App
 * This is an awesome app!
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * User information for chat messages
 * @export
 * @interface MessageUserDTO
 */
export interface MessageUserDTO {
    /**
     * User unique identifier
     * @type {number}
     * @memberof MessageUserDTO
     */
    id: number;
    /**
     * User email address
     * @type {string}
     * @memberof MessageUserDTO
     */
    email: string;
}

/**
 * Check if a given object implements the MessageUserDTO interface.
 */
export function instanceOfMessageUserDTO(value: object): value is MessageUserDTO {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function MessageUserDTOFromJSON(json: any): MessageUserDTO {
    return MessageUserDTOFromJSONTyped(json, false);
}

export function MessageUserDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): MessageUserDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['_id'],
        'email': json['email'],
    };
}

export function MessageUserDTOToJSON(json: any): MessageUserDTO {
    return MessageUserDTOToJSONTyped(json, false);
}

export function MessageUserDTOToJSONTyped(value?: MessageUserDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        '_id': value['id'],
        'email': value['email'],
    };
}

