/* tslint:disable */
/* eslint-disable */
/**
 * My App
 * This is an awesome app!
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MessageUserDTO } from './MessageUserDTO';
import {
    MessageUserDTOFromJSON,
    MessageUserDTOFromJSONTyped,
    MessageUserDTOToJSON,
    MessageUserDTOToJSONTyped,
} from './MessageUserDTO';

/**
 * Chat message data transfer object
 * @export
 * @interface MessageDTO
 */
export interface MessageDTO {
    /**
     * Unique message identifier
     * @type {number}
     * @memberof MessageDTO
     */
    id: number;
    /**
     * Message content
     * @type {string}
     * @memberof MessageDTO
     */
    text: string;
    /**
     * Timestamp in milliseconds when the message was created
     * @type {number}
     * @memberof MessageDTO
     */
    createdAt: number;
    /**
     * 
     * @type {MessageUserDTO}
     * @memberof MessageDTO
     */
    user: MessageUserDTO;
    /**
     * True if message was sent by current user
     * @type {boolean}
     * @memberof MessageDTO
     */
    sent: boolean;
    /**
     * True if message was received by current user
     * @type {boolean}
     * @memberof MessageDTO
     */
    received: boolean;
    /**
     * Optional image URL
     * @type {string}
     * @memberof MessageDTO
     */
    image?: string | null;
    /**
     * True if this is a system message
     * @type {boolean}
     * @memberof MessageDTO
     */
    system?: boolean | null;
    /**
     * True if message is pending delivery
     * @type {boolean}
     * @memberof MessageDTO
     */
    pending?: boolean | null;
}

/**
 * Check if a given object implements the MessageDTO interface.
 */
export function instanceOfMessageDTO(value: object): value is MessageDTO {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('text' in value) || value['text'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('user' in value) || value['user'] === undefined) return false;
    if (!('sent' in value) || value['sent'] === undefined) return false;
    if (!('received' in value) || value['received'] === undefined) return false;
    return true;
}

export function MessageDTOFromJSON(json: any): MessageDTO {
    return MessageDTOFromJSONTyped(json, false);
}

export function MessageDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): MessageDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['_id'],
        'text': json['text'],
        'createdAt': json['createdAt'],
        'user': MessageUserDTOFromJSON(json['user']),
        'sent': json['sent'],
        'received': json['received'],
        'image': json['image'] == null ? undefined : json['image'],
        'system': json['system'] == null ? undefined : json['system'],
        'pending': json['pending'] == null ? undefined : json['pending'],
    };
}

export function MessageDTOToJSON(json: any): MessageDTO {
    return MessageDTOToJSONTyped(json, false);
}

export function MessageDTOToJSONTyped(value?: MessageDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        '_id': value['id'],
        'text': value['text'],
        'createdAt': value['createdAt'],
        'user': MessageUserDTOToJSON(value['user']),
        'sent': value['sent'],
        'received': value['received'],
        'image': value['image'],
        'system': value['system'],
        'pending': value['pending'],
    };
}

