/* tslint:disable */
/* eslint-disable */
/**
 * My App
 * This is an awesome app!
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostAppSpecautocontextPresentationSpecautocreateCreateRequest
 */
export interface PostAppSpecautocontextPresentationSpecautocreateCreateRequest {
    /**
     * 
     * @type {string}
     * @memberof PostAppSpecautocontextPresentationSpecautocreateCreateRequest
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof PostAppSpecautocontextPresentationSpecautocreateCreateRequest
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof PostAppSpecautocontextPresentationSpecautocreateCreateRequest
     */
    price?: string;
    /**
     * 
     * @type {string}
     * @memberof PostAppSpecautocontextPresentationSpecautocreateCreateRequest
     */
    currency?: string;
    /**
     * 
     * @type {string}
     * @memberof PostAppSpecautocontextPresentationSpecautocreateCreateRequest
     */
    region?: string;
    /**
     * 
     * @type {number}
     * @memberof PostAppSpecautocontextPresentationSpecautocreateCreateRequest
     */
    releaseYear?: number;
    /**
     * 
     * @type {Array<object>}
     * @memberof PostAppSpecautocontextPresentationSpecautocreateCreateRequest
     */
    parameters?: Array<object>;
}

/**
 * Check if a given object implements the PostAppSpecautocontextPresentationSpecautocreateCreateRequest interface.
 */
export function instanceOfPostAppSpecautocontextPresentationSpecautocreateCreateRequest(value: object): value is PostAppSpecautocontextPresentationSpecautocreateCreateRequest {
    return true;
}

export function PostAppSpecautocontextPresentationSpecautocreateCreateRequestFromJSON(json: any): PostAppSpecautocontextPresentationSpecautocreateCreateRequest {
    return PostAppSpecautocontextPresentationSpecautocreateCreateRequestFromJSONTyped(json, false);
}

export function PostAppSpecautocontextPresentationSpecautocreateCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostAppSpecautocontextPresentationSpecautocreateCreateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'price': json['price'] == null ? undefined : json['price'],
        'currency': json['currency'] == null ? undefined : json['currency'],
        'region': json['region'] == null ? undefined : json['region'],
        'releaseYear': json['releaseYear'] == null ? undefined : json['releaseYear'],
        'parameters': json['parameters'] == null ? undefined : json['parameters'],
    };
}

export function PostAppSpecautocontextPresentationSpecautocreateCreateRequestToJSON(json: any): PostAppSpecautocontextPresentationSpecautocreateCreateRequest {
    return PostAppSpecautocontextPresentationSpecautocreateCreateRequestToJSONTyped(json, false);
}

export function PostAppSpecautocontextPresentationSpecautocreateCreateRequestToJSONTyped(value?: PostAppSpecautocontextPresentationSpecautocreateCreateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'price': value['price'],
        'currency': value['currency'],
        'region': value['region'],
        'releaseYear': value['releaseYear'],
        'parameters': value['parameters'],
    };
}

