/* tslint:disable */
/* eslint-disable */
/**
 * My App
 * This is an awesome app!
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RegisterPushTokenRequest
 */
export interface RegisterPushTokenRequest {
    /**
     * Expo push token
     * @type {string}
     * @memberof RegisterPushTokenRequest
     */
    expoPushToken: string;
    /**
     * Platform type
     * @type {string}
     * @memberof RegisterPushTokenRequest
     */
    platform: RegisterPushTokenRequestPlatformEnum;
    /**
     * Unique device identifier
     * @type {string}
     * @memberof RegisterPushTokenRequest
     */
    deviceId: string;
    /**
     * Human-readable device name
     * @type {string}
     * @memberof RegisterPushTokenRequest
     */
    deviceName?: string | null;
}


/**
 * @export
 */
export const RegisterPushTokenRequestPlatformEnum = {
    Ios: 'ios',
    Android: 'android',
    Web: 'web'
} as const;
export type RegisterPushTokenRequestPlatformEnum = typeof RegisterPushTokenRequestPlatformEnum[keyof typeof RegisterPushTokenRequestPlatformEnum];


/**
 * Check if a given object implements the RegisterPushTokenRequest interface.
 */
export function instanceOfRegisterPushTokenRequest(value: object): value is RegisterPushTokenRequest {
    if (!('expoPushToken' in value) || value['expoPushToken'] === undefined) return false;
    if (!('platform' in value) || value['platform'] === undefined) return false;
    if (!('deviceId' in value) || value['deviceId'] === undefined) return false;
    return true;
}

export function RegisterPushTokenRequestFromJSON(json: any): RegisterPushTokenRequest {
    return RegisterPushTokenRequestFromJSONTyped(json, false);
}

export function RegisterPushTokenRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterPushTokenRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'expoPushToken': json['expoPushToken'],
        'platform': json['platform'],
        'deviceId': json['deviceId'],
        'deviceName': json['deviceName'] == null ? undefined : json['deviceName'],
    };
}

export function RegisterPushTokenRequestToJSON(json: any): RegisterPushTokenRequest {
    return RegisterPushTokenRequestToJSONTyped(json, false);
}

export function RegisterPushTokenRequestToJSONTyped(value?: RegisterPushTokenRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'expoPushToken': value['expoPushToken'],
        'platform': value['platform'],
        'deviceId': value['deviceId'],
        'deviceName': value['deviceName'],
    };
}

