/* tslint:disable */
/* eslint-disable */
/**
 * My App
 * This is an awesome app!
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SendNotificationRequest
 */
export interface SendNotificationRequest {
    /**
     * Notification title
     * @type {string}
     * @memberof SendNotificationRequest
     */
    title: string;
    /**
     * Notification body
     * @type {string}
     * @memberof SendNotificationRequest
     */
    body: string;
    /**
     * User ID to send to (optional, if not provided sends to all active tokens)
     * @type {number}
     * @memberof SendNotificationRequest
     */
    userId?: number;
    /**
     * Additional data payload
     * @type {object}
     * @memberof SendNotificationRequest
     */
    data?: object;
    /**
     * Notification provider to use
     * @type {string}
     * @memberof SendNotificationRequest
     */
    provider?: SendNotificationRequestProviderEnum;
}


/**
 * @export
 */
export const SendNotificationRequestProviderEnum = {
    Expo: 'expo',
    Firebase: 'firebase'
} as const;
export type SendNotificationRequestProviderEnum = typeof SendNotificationRequestProviderEnum[keyof typeof SendNotificationRequestProviderEnum];


/**
 * Check if a given object implements the SendNotificationRequest interface.
 */
export function instanceOfSendNotificationRequest(value: object): value is SendNotificationRequest {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('body' in value) || value['body'] === undefined) return false;
    return true;
}

export function SendNotificationRequestFromJSON(json: any): SendNotificationRequest {
    return SendNotificationRequestFromJSONTyped(json, false);
}

export function SendNotificationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendNotificationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'body': json['body'],
        'userId': json['userId'] == null ? undefined : json['userId'],
        'data': json['data'] == null ? undefined : json['data'],
        'provider': json['provider'] == null ? undefined : json['provider'],
    };
}

export function SendNotificationRequestToJSON(json: any): SendNotificationRequest {
    return SendNotificationRequestToJSONTyped(json, false);
}

export function SendNotificationRequestToJSONTyped(value?: SendNotificationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'body': value['body'],
        'userId': value['userId'],
        'data': value['data'],
        'provider': value['provider'],
    };
}

