/* tslint:disable */
/* eslint-disable */
/**
 * My App
 * This is an awesome app!
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SimpleAutoGenerationModificationsInner
 */
export interface SimpleAutoGenerationModificationsInner {
    /**
     * 
     * @type {number}
     * @memberof SimpleAutoGenerationModificationsInner
     */
    id: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof SimpleAutoGenerationModificationsInner
     */
    frames: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof SimpleAutoGenerationModificationsInner
     */
    restyling: number;
    /**
     * 
     * @type {number}
     * @memberof SimpleAutoGenerationModificationsInner
     */
    yearStart: number;
    /**
     * 
     * @type {number}
     * @memberof SimpleAutoGenerationModificationsInner
     */
    yearEnd: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof SimpleAutoGenerationModificationsInner
     */
    images: Array<string>;
}

/**
 * Check if a given object implements the SimpleAutoGenerationModificationsInner interface.
 */
export function instanceOfSimpleAutoGenerationModificationsInner(value: object): value is SimpleAutoGenerationModificationsInner {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('frames' in value) || value['frames'] === undefined) return false;
    if (!('restyling' in value) || value['restyling'] === undefined) return false;
    if (!('yearStart' in value) || value['yearStart'] === undefined) return false;
    if (!('yearEnd' in value) || value['yearEnd'] === undefined) return false;
    if (!('images' in value) || value['images'] === undefined) return false;
    return true;
}

export function SimpleAutoGenerationModificationsInnerFromJSON(json: any): SimpleAutoGenerationModificationsInner {
    return SimpleAutoGenerationModificationsInnerFromJSONTyped(json, false);
}

export function SimpleAutoGenerationModificationsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): SimpleAutoGenerationModificationsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'frames': json['frames'],
        'restyling': json['restyling'],
        'yearStart': json['yearStart'],
        'yearEnd': json['yearEnd'],
        'images': json['images'],
    };
}

export function SimpleAutoGenerationModificationsInnerToJSON(json: any): SimpleAutoGenerationModificationsInner {
    return SimpleAutoGenerationModificationsInnerToJSONTyped(json, false);
}

export function SimpleAutoGenerationModificationsInnerToJSONTyped(value?: SimpleAutoGenerationModificationsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'frames': value['frames'],
        'restyling': value['restyling'],
        'yearStart': value['yearStart'],
        'yearEnd': value['yearEnd'],
        'images': value['images'],
    };
}

