/* tslint:disable */
/* eslint-disable */
/**
 * My App
 * This is an awesome app!
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SimpleAutoAdvertisement
 */
export interface SimpleAutoAdvertisement {
    /**
     * 
     * @type {number}
     * @memberof SimpleAutoAdvertisement
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof SimpleAutoAdvertisement
     */
    brand: string;
    /**
     * 
     * @type {string}
     * @memberof SimpleAutoAdvertisement
     */
    model: string;
    /**
     * 
     * @type {string}
     * @memberof SimpleAutoAdvertisement
     */
    price: string;
    /**
     * 
     * @type {string}
     * @memberof SimpleAutoAdvertisement
     */
    currency: string;
    /**
     * 
     * @type {number}
     * @memberof SimpleAutoAdvertisement
     */
    releaseYear: number;
    /**
     * 
     * @type {string}
     * @memberof SimpleAutoAdvertisement
     */
    region: string;
    /**
     * 
     * @type {Date}
     * @memberof SimpleAutoAdvertisement
     */
    createdAt: Date;
    /**
     * 
     * @type {Array<string>}
     * @memberof SimpleAutoAdvertisement
     */
    images: Array<string>;
}

/**
 * Check if a given object implements the SimpleAutoAdvertisement interface.
 */
export function instanceOfSimpleAutoAdvertisement(value: object): value is SimpleAutoAdvertisement {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('brand' in value) || value['brand'] === undefined) return false;
    if (!('model' in value) || value['model'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('releaseYear' in value) || value['releaseYear'] === undefined) return false;
    if (!('region' in value) || value['region'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('images' in value) || value['images'] === undefined) return false;
    return true;
}

export function SimpleAutoAdvertisementFromJSON(json: any): SimpleAutoAdvertisement {
    return SimpleAutoAdvertisementFromJSONTyped(json, false);
}

export function SimpleAutoAdvertisementFromJSONTyped(json: any, ignoreDiscriminator: boolean): SimpleAutoAdvertisement {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'brand': json['brand'],
        'model': json['model'],
        'price': json['price'],
        'currency': json['currency'],
        'releaseYear': json['releaseYear'],
        'region': json['region'],
        'createdAt': (new Date(json['createdAt'])),
        'images': json['images'],
    };
}

export function SimpleAutoAdvertisementToJSON(json: any): SimpleAutoAdvertisement {
    return SimpleAutoAdvertisementToJSONTyped(json, false);
}

export function SimpleAutoAdvertisementToJSONTyped(value?: SimpleAutoAdvertisement | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'brand': value['brand'],
        'model': value['model'],
        'price': value['price'],
        'currency': value['currency'],
        'releaseYear': value['releaseYear'],
        'region': value['region'],
        'createdAt': value['createdAt'].toISOString(),
        'images': value['images'],
    };
}

