/* tslint:disable */
/* eslint-disable */
/**
 * My App
 * This is an awesome app!
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SimpleAutoGenerationModificationsInner } from './SimpleAutoGenerationModificationsInner';
import {
    SimpleAutoGenerationModificationsInnerFromJSON,
    SimpleAutoGenerationModificationsInnerFromJSONTyped,
    SimpleAutoGenerationModificationsInnerToJSON,
    SimpleAutoGenerationModificationsInnerToJSONTyped,
} from './SimpleAutoGenerationModificationsInner';

/**
 * 
 * @export
 * @interface SimpleAutoGeneration
 */
export interface SimpleAutoGeneration {
    /**
     * 
     * @type {number}
     * @memberof SimpleAutoGeneration
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof SimpleAutoGeneration
     */
    generation: number;
    /**
     * 
     * @type {Array<SimpleAutoGenerationModificationsInner>}
     * @memberof SimpleAutoGeneration
     */
    modifications: Array<SimpleAutoGenerationModificationsInner>;
}

/**
 * Check if a given object implements the SimpleAutoGeneration interface.
 */
export function instanceOfSimpleAutoGeneration(value: object): value is SimpleAutoGeneration {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('generation' in value) || value['generation'] === undefined) return false;
    if (!('modifications' in value) || value['modifications'] === undefined) return false;
    return true;
}

export function SimpleAutoGenerationFromJSON(json: any): SimpleAutoGeneration {
    return SimpleAutoGenerationFromJSONTyped(json, false);
}

export function SimpleAutoGenerationFromJSONTyped(json: any, ignoreDiscriminator: boolean): SimpleAutoGeneration {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'generation': json['generation'],
        'modifications': ((json['modifications'] as Array<any>).map(SimpleAutoGenerationModificationsInnerFromJSON)),
    };
}

export function SimpleAutoGenerationToJSON(json: any): SimpleAutoGeneration {
    return SimpleAutoGenerationToJSONTyped(json, false);
}

export function SimpleAutoGenerationToJSONTyped(value?: SimpleAutoGeneration | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'generation': value['generation'],
        'modifications': ((value['modifications'] as Array<any>).map(SimpleAutoGenerationModificationsInnerToJSON)),
    };
}

