/* tslint:disable */
/* eslint-disable */
/**
 * My App
 * This is an awesome app!
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TestNotificationRequest
 */
export interface TestNotificationRequest {
    /**
     * User ID to send notification to (optional, if not provided sends to all active tokens)
     * @type {number}
     * @memberof TestNotificationRequest
     */
    userId?: number | null;
    /**
     * Notification title
     * @type {string}
     * @memberof TestNotificationRequest
     */
    title: string;
    /**
     * Notification body
     * @type {string}
     * @memberof TestNotificationRequest
     */
    body: string;
}

/**
 * Check if a given object implements the TestNotificationRequest interface.
 */
export function instanceOfTestNotificationRequest(value: object): value is TestNotificationRequest {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('body' in value) || value['body'] === undefined) return false;
    return true;
}

export function TestNotificationRequestFromJSON(json: any): TestNotificationRequest {
    return TestNotificationRequestFromJSONTyped(json, false);
}

export function TestNotificationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TestNotificationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'] == null ? undefined : json['userId'],
        'title': json['title'],
        'body': json['body'],
    };
}

export function TestNotificationRequestToJSON(json: any): TestNotificationRequest {
    return TestNotificationRequestToJSONTyped(json, false);
}

export function TestNotificationRequestToJSONTyped(value?: TestNotificationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
        'title': value['title'],
        'body': value['body'],
    };
}

