/* tslint:disable */
/* eslint-disable */
/**
 * My App
 * This is an awesome app!
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserSignUpDTO
 */
export interface UserSignUpDTO {
    /**
     * 
     * @type {string}
     * @memberof UserSignUpDTO
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof UserSignUpDTO
     */
    phoneNumber: string;
    /**
     * 
     * @type {string}
     * @memberof UserSignUpDTO
     */
    password: string;
}

/**
 * Check if a given object implements the UserSignUpDTO interface.
 */
export function instanceOfUserSignUpDTO(value: object): value is UserSignUpDTO {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('phoneNumber' in value) || value['phoneNumber'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function UserSignUpDTOFromJSON(json: any): UserSignUpDTO {
    return UserSignUpDTOFromJSONTyped(json, false);
}

export function UserSignUpDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserSignUpDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'phoneNumber': json['phoneNumber'],
        'password': json['password'],
    };
}

export function UserSignUpDTOToJSON(json: any): UserSignUpDTO {
    return UserSignUpDTOToJSONTyped(json, false);
}

export function UserSignUpDTOToJSONTyped(value?: UserSignUpDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'phoneNumber': value['phoneNumber'],
        'password': value['password'],
    };
}

