/* tslint:disable */
/* eslint-disable */
/**
 * My App
 * This is an awesome app!
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserSubscriptionFilter
 */
export interface UserSubscriptionFilter {
    /**
     * 
     * @type {number}
     * @memberof UserSubscriptionFilter
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof UserSubscriptionFilter
     */
    name: string;
    /**
     * 
     * @type {{ [key: string]: Array<string>; }}
     * @memberof UserSubscriptionFilter
     */
    filters: { [key: string]: Array<string>; };
}

/**
 * Check if a given object implements the UserSubscriptionFilter interface.
 */
export function instanceOfUserSubscriptionFilter(value: object): value is UserSubscriptionFilter {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('filters' in value) || value['filters'] === undefined) return false;
    return true;
}

export function UserSubscriptionFilterFromJSON(json: any): UserSubscriptionFilter {
    return UserSubscriptionFilterFromJSONTyped(json, false);
}

export function UserSubscriptionFilterFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserSubscriptionFilter {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'filters': json['filters'],
    };
}

export function UserSubscriptionFilterToJSON(json: any): UserSubscriptionFilter {
    return UserSubscriptionFilterToJSONTyped(json, false);
}

export function UserSubscriptionFilterToJSONTyped(value?: UserSubscriptionFilter | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'filters': value['filters'],
    };
}

