/* tslint:disable */
/* eslint-disable */
/**
 * My App
 * This is an awesome app!
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * User advertisement item response
 * @export
 * @interface UserAdvertisementItemResponse
 */
export interface UserAdvertisementItemResponse {
    /**
     * 
     * @type {string}
     * @memberof UserAdvertisementItemResponse
     */
    description: string;
    /**
     * 
     * @type {boolean}
     * @memberof UserAdvertisementItemResponse
     */
    isVerified: boolean;
    /**
     * 
     * @type {Date}
     * @memberof UserAdvertisementItemResponse
     */
    updatedAt: Date;
    /**
     * 
     * @type {number}
     * @memberof UserAdvertisementItemResponse
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof UserAdvertisementItemResponse
     */
    brand: string;
    /**
     * 
     * @type {string}
     * @memberof UserAdvertisementItemResponse
     */
    model: string;
    /**
     * 
     * @type {string}
     * @memberof UserAdvertisementItemResponse
     */
    price: string;
    /**
     * 
     * @type {string}
     * @memberof UserAdvertisementItemResponse
     */
    currency: string;
    /**
     * 
     * @type {number}
     * @memberof UserAdvertisementItemResponse
     */
    releaseYear: number;
    /**
     * 
     * @type {string}
     * @memberof UserAdvertisementItemResponse
     */
    region: string;
    /**
     * 
     * @type {Date}
     * @memberof UserAdvertisementItemResponse
     */
    createdAt: Date;
    /**
     * 
     * @type {Array<string>}
     * @memberof UserAdvertisementItemResponse
     */
    images?: Array<string>;
}

/**
 * Check if a given object implements the UserAdvertisementItemResponse interface.
 */
export function instanceOfUserAdvertisementItemResponse(value: object): value is UserAdvertisementItemResponse {
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('isVerified' in value) || value['isVerified'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('brand' in value) || value['brand'] === undefined) return false;
    if (!('model' in value) || value['model'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('releaseYear' in value) || value['releaseYear'] === undefined) return false;
    if (!('region' in value) || value['region'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function UserAdvertisementItemResponseFromJSON(json: any): UserAdvertisementItemResponse {
    return UserAdvertisementItemResponseFromJSONTyped(json, false);
}

export function UserAdvertisementItemResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserAdvertisementItemResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'],
        'isVerified': json['isVerified'],
        'updatedAt': (new Date(json['updatedAt'])),
        'id': json['id'],
        'brand': json['brand'],
        'model': json['model'],
        'price': json['price'],
        'currency': json['currency'],
        'releaseYear': json['releaseYear'],
        'region': json['region'],
        'createdAt': (new Date(json['createdAt'])),
        'images': json['images'] == null ? undefined : json['images'],
    };
}

export function UserAdvertisementItemResponseToJSON(json: any): UserAdvertisementItemResponse {
    return UserAdvertisementItemResponseToJSONTyped(json, false);
}

export function UserAdvertisementItemResponseToJSONTyped(value?: UserAdvertisementItemResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'isVerified': value['isVerified'],
        'updatedAt': value['updatedAt'].toISOString(),
        'id': value['id'],
        'brand': value['brand'],
        'model': value['model'],
        'price': value['price'],
        'currency': value['currency'],
        'releaseYear': value['releaseYear'],
        'region': value['region'],
        'createdAt': value['createdAt'].toISOString(),
        'images': value['images'],
    };
}

